src/markdown-pages/collect-data/get-started-nerdgraph-api-explorer.mdx

Closes #280
Adds the getting started video for the NerdGraph API doc.

Add the NerdGraph getting started video

---

src/markdown-pages/collect-data/collect-data-from-any-source.mdx

This PR makes all the API request examples on the "Collect Data" page match...
* Each example is based on `curl` using the same style
* Uses `$VARIABLES` instead of placeholders so these commands can be executed as-is w/o editing them
* Removes the python example code which is tangential to showing how to use the Events API

Make API request examples match

---

src/components/NewRelicIcon.js

Replaces the 'Build apps' icon with the Apps icon from the product for consistency.
* [DEVEX-1119](https://newrelic.atlassian.net/browse/DEVEX-1119)

Replace build apps icon with product icon

---

README.md

Adds the OSS banner to the README
[Rendered](https://github.com/newrelic/developer-website/blob/jerel/oss-banner/README.md)

Add OSS banner to README

---

src/components/Seo.js

Google Search Console requires us to verify ownership of the domain. This meta tag will handle that for us. This also includes some lint cleanup.
We can probably remove this once we have gone through the verification process.
Closes #345

Add Google verification header for search console

---

src/components/PropList.module.scss

Fixes an issue where prop definitions were overlapping on mobile. The prop name / required flag were overlapping with the description due to being in a two-column layout.
On very narrow displays, the page has a sideways scrollbar. I was unable to determine which element was pushing out the width, but I wanted to get the fix in place for the prop overlap since it's a high-priority issue.
Closes #343
**BEFORE**
**AFTER**

Fix prop overlap issue on mobile

---

src/components/SearchInput.module.scss

Adds a small bit of margin in hamburger view to prevent the overlap from happening
#335

Fix search input overlap in hamburger menu view.

---

src/components/Step.module.scss

The guide step number and title should be connected visually, which we accomplish by reducing the spacing between these elements.

fix: Reduce spacing between guide step and title

---

src/pages/index.js
src/pages/index.module.scss

We can do a better job of incorporating the developer champion badge into its box on the landing page. This PR moves the badge to the right of the box and increases the size so it's more prominent.

Relocate developer champion badge on landing page

---

src/pages/index.js

The developer champions banner on the landing page should really link to the developer champions page! This PR adds a link to do just that.
I also update the casing of both buttons to be sentence case to match the title of the banner.

Add link to dev champions page from landing page

---

src/templates/OverviewTemplate.js
src/templates/OverviewTemplate.module.scss

Creates subheaders on the overview pages for the guide tiles
Closes #316

Subheaders in overview pages

---

src/markdown-pages/build-apps/build-hello-world-app.mdx

Partially addresses #401 
Removes the quotes from the URL that describes where to visit when running local nerdpacks. This was a typo.

Remove quotes in the local build URL

---

src/markdown-pages/build-apps/add-time-picker-guide.mdx

Partially addresses #401 
Fixes indentation on one of the code samples for the time picker guide. The code sample is not syntactically valid, so the automatic code formatting does not kick in properly. This PR manually adds the proper indentation so that the code sample shows up in a cleaner format. 
This updates step 3/5 under the `Import the PlatformStateContext component` section on the [add time picker guide](https://developer.newrelic.com/build-apps/add-time-picker-guide)

Fix indentation for a code sample in the add time picker guide

---

src/components/IconReference.js

Copies to clipboard with the `Icon.TYPE.` prefix
Go to the icon gallery and clip the copy to clipboard for one of the icons. 
Closes #395

copies to clipboard with `icon.TYPE.` prefix

---

src/components/NavigationItems.js
src/data/sidenav.json

This PR moves our existing intro to the SDK page into the component library side nav item. Instead of remaining a toggle, the component library will now land on the intro page as well as expand the sub nav of components.
Closes #306

Move component overview page into component library side nav item

---

.github/workflows/changelog.yml
.github/workflows/release.yml
.releaserc

Adds a GitHub Action to generate a [semantic release](https://github.com/semantic-release/semantic-release) (and generate a changelog) whenever we merge into `master`. Much of this was taken from [what the OSS had set up](https://github.com/newrelic/opensource-website/blob/develop/.github/workflows/release.yml#L114-L153).
This will get kicked off when it gets merged into master. The only thing I was unsure about was the `Cache node_modules` step.
Closes #301

GitHub Action to Generate Changelog

---

src/components/Layout.js

Fixes a bug in which the value of a cookie was expected to be a boolean but was a string

chore: Check string value instead of boolean

---

src/components/NavigationItems.js
src/components/NavigationItems.module.scss

While we still don't have a full fix for #456, this PR at least maintains the bold styling on non toggle-able nav items (collect data, automate workflows, build apps) after refresh
Try navigating to a page within collect data, automate workflows, or build apps. Refresh the page to see the bold styling preserved
Partial fix for #456

Persist bold style in Link nav items

---

src/pages/podcasts.js

This swaps out the player URL so multiple episodes will appear; the original embed was using the single episode player.
The player should automatically show new episodes after this gets deployed.

Use multi-episode player link.

---

src/markdown-pages/explore-docs/nr1-catalog.mdx
src/markdown-pages/explore-docs/nr1-common.mdx
src/markdown-pages/explore-docs/nr1-config.mdx
src/markdown-pages/explore-docs/nr1-nerdpack.mdx
src/markdown-pages/explore-docs/nr1-plugins.mdx
src/markdown-pages/explore-docs/nr1-subscription.mdx

One of our recently merged markdown files had empty frontmatter which was causing Gatsby to fail when building. Adding `''` as the value resolves this.

Fix build by resolving issue with Frontmatter

---

src/markdown-pages/explore-docs/nr1-cli.mdx

This PR fixes broken links in the New Relic One CLI docs for subscription commands.

Fix broken links on subscription commands

---

src/components/Seo.js
src/markdown-pages/automate-workflows/get-started-new-relic-cli.mdx
src/markdown-pages/automate-workflows/get-started-terraform.mdx
src/markdown-pages/build-apps/build-hello-world-app.mdx
src/markdown-pages/collect-data/add-custom-attributes.mdx
src/markdown-pages/collect-data/collect-data-from-any-source.mdx
src/markdown-pages/explore-docs/newrelic-CLI.mdx
src/markdown-pages/explore-docs/nr1-cli.mdx
src/templates/GuideTemplate.js

Relates to #541 
Closes #539 
This PR sets up the tagging mechanism defined in frontmatter so that we can index the tags with Swiftype. Once we get the tags defined from #539 we can add tags in this PR on all of the guides we want to test with.

Index tags for a guide

---

src/pages/developer-champion.module.scss
src/pages/podcasts.js
src/pages/podcasts.module.scss

On the **podcasts** and **developer champion** pages, the current style rules enforce a 2 and even 3 column layout on mobile devices.
This PR applies single column styles on those pages until the breakpoint used throughout the codebase `@media (max-width: 760px)`
1. Go to `/podcasts` or `/developer-champion` on a mobile device or in a viewport narrower than `760px`
2. Note that these layouts are single columned for the main body content, and only apply the 2 and 3 column rules from `760px` and wider
Addresses: [2- and 3-column grid layouts on mobile devices](https://github.com/newrelic/developer-website/issues/568)

Add responsive columns to developer champion and podcast pages

---

src/markdown-pages/build-apps/howto-use-nrone-table-components.mdx

Removes the empty "Related info" section at the bottom of the table guide.

Remove empty related info section on a guide

---

src/components/RelatedContentModules/Resources.js

Reduces font size on the resources links to try and save some vertical space
when possible.
**Before**
**After**

Reduce font size on resources links

---

src/components/RelatedContentModules/Resources.js

This PR changes the right rail's `Resources` text to `Related resources`
It also applies uppercase to the tags' text
Closes #581 Partially addresses #561

Change resources title and uppercase tag text

---

.github/workflows/fetch-related-content.yml

Closes #582 
Adds a GitHub action that will fetch search results for all mdx pages and store them in a JSON file. This will commit those changes and push to the `main` branch to redeploy. This is currently set to run every day.

Add a GitHub action that will run everyday to sync swiftype results

---

src/components/RelatedContentModules/Resources.js

Hides the "Related resources" section for pages that have not been indexed. Also
reduces the font-size a tad on the related resources section.
**Before**
**After**

Hide related resources for pages that are not yet indexed

---

src/markdown-pages/collect-data/get-started-nerdgraph-api-explorer.mdx

Use `graphql` syntax highlighting for GraphQL code blocks on the NerdGraph API Explorer guide.

docs: use graphql syntax highlighting for gql

---

src/components/Iframe.js
src/components/MDXContainer.js
src/components/RelatedContentModules/PageUpdated.js

Adds some minor adjustments to `iframe`s added to guides. At the moment, we are simply making them full-width and ensuring a `title` property is added (for accesability). In the future, we can use this component to provide additional styling, a mobile-fallback-message, or limit what gets built (for security).
This also fixes a small issue where the "Last updated" message shows "Invalid date". It's likely that we would never run into that condition, but just in case I added a check.
To test this, I made a test markdown page with an `iframe` in it. See the related PR (linked below) for an example of how this would be used and the screenshots section for how that page would be rendered.
* Closes #593 
* Relates to #596 
**Desktop**
**Mobile**

Styles for `iframe`s within Guides

---

src/pages/kubecon-europe-2020.module.scss

The recently-added kubecon landing page had some issues with responsiveness (specifically around the tablet breakpoint). This makes a few adjustments to resolve this (as well as updates the scss file for scss).
This is a quick fix for Kubecon. At some point, we should update this to use emotion.
N/A
**Before**
**After**

Style adjustments on kubecon page

---

src/components/FeatherIcon.js
src/data/sidenav.json

Adds a side bar nav item called Attend events.
Moves the kubecon event page under that nav item

added events to side nav

---

src/components/FeatherIcon.js
src/components/NavigationItems.js

Work to get the feather icon to appear from the attend event side navigation using an if statement. This isn't working yet, but it's super close so I'm handing it off to @jerelmiller  the "closer"

Attend event icon logic 

---

src/components/Sidebar.js

Fixes the logo height rendering issue in Safari
**Before**
**After**

Fix logo rendering issue in Safari

---

package-lock.json
package.json
src/components/Logo.module.scss
src/components/RelatedContentModules/Contribute.js
src/components/styles.scss
src/layouts/MainLayout.js
src/pages/developer-champion.module.scss
src/pages/index.js
src/pages/kubecon-europe-2020.module.scss

Closes #536 
Upgrades `gatsby-theme-newrelic` to add the sign up button. Updates the brand colors to match the latest color palette. Update `PLAIN` buttons to use the proper button styles.

Upgrade Gatsby theme to get sign up button + other goodies

---

src/data/additionalDocs.js
src/hooks/useApiDoc.js

The bundle that we use to generate documentation for components and APIs is missing information. One example is the `nerdlet.setUrlState` method. In order to help provide more complete documentation, I created a system for us to add additional documentation that we define. This (temporary) solution should allow us to add in any missing methods, typeDefs, or constants.
At the moment, I have just added the `nerdlet.setUrlState` method documentation (as the linked ticket suggests). Please let me know what you think of this setup / naming convention.
* Closes #450 
The first method in this screenshot is defined by us, the rest come from the bundle:

Add the ability to provide supplemental API documentation

---

package-lock.json
package.json

Closes #629 
Bumps the `@newrelic/gatsby-theme-newrelic` version to get the latest changes.

Bump @newrelic/gatsby-theme-newrelic version

---

STYLE_GUIDE.md
src/markdown-pages/collect-data/get-started-nerdgraph-api-explorer.mdx
src/markdown-pages/collect-data/query-data-nrql.mdx

- added nrql lessons to resources
- fixed a missing ' ' on the resource titles on the get-started-nerdgraph-api-explorer page 
- updated style guide to specify you need single quotes around resource titles.

added nrql lessons to page frontmatter resources

---

.github/workflows/release.yml

Closes #650 
Enabled branch protection in the repo. This PR will temporarily disable it when pushing commits in the release action by the bot.

Temp disable/re-enable branch protection rules for GH actions

---

src/components/NavigationItems.js
src/data/sidenav.json

- Added a past events section to the Attend Events nav
- Changed the attend events nav item to Developer Events
- Added nerd days 1.0 to event nav section
#672

added second level to events nav

---

src/components/GuideTile/GuideTile.js
src/pages/index.js

Closes #642 
Updates the collect data icon on the main page to use the new icon

Update collect data icon on main page

---

src/pages/index.js

Updating countdown to reflect countdown to Nerd Days and removing CFP messaging.
Do not merge this until Sept. 2 after call for proposals are closed. 
https://github.com/newrelic/developer-website/issues/704

Update countdown timer after CFP closes

---

src/pages/index.js

Reverts newrelic/developer-website#705
I missed the note about this being time-sensitive.

Revert "Update countdown timer after CFP closes"

---

gatsby-config.js
gatsby-node.js
package-lock.json
package.json
src/layouts/MainLayout.js

Closes #645 
Closes #655 
Sets up split integration for the site. Will also conditionally add the github buttons to the header based on the treatments of the split.

Split.io integration

---

gatsby-config.js
package-lock.json
package.json
src/components/PageLayout/PageLayout.js
src/components/RelatedContentModules/Contribute.js
src/data/constants.js
src/hooks/useTreatment.js

Closes #643 
Adds an A/B test for the right rail button treatment. One treatment will keep the buttons like they are and the other treatment will show the outline button variant. The buttons are tracked via the `related_content.contribute_action_clicked` event.

Right-rail A/B test on buttons

---

gatsby-node.js
package-lock.json
package.json
src/hooks/useResizeObserver.js
src/layouts/MainLayout.js

This addresses a few issues that are specific to the developer site when it comes to using the _Announcement Banner_:
* Fixes an issue where Gatsby would try to create a new page for an announcement MDX file
* Fixes an issue where the sidebar was appearing _under_ the header when a banner was present
I added a hook called `useResizeObserver` that uses [ResizeObserver](https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver) under the hood. This may be helpful in other locations. At the moment, it's just set up to work with height, but we can make it more generalized if we want.
N/A
**With a Banner:**
**Without a Banner:**

Announcement Banner Fixes

---

src/pages/nerd-days.module.scss

Add back missing styles preventing the 2-column layout on the nerd days pages from showing up correctly.
**Before**
**After**

Add back missing styles removed from nerd days redesign

---

src/pages/nerd-days.js
src/pages/nerd-days.module.scss

removed custom css font properties on CtaItem to allow dark mode toggle to work correctly.
increased date font size for readability 
removed extra line from css file

remove custom css font properties to allow dark mode toggle to work on text

---

gatsby-browser.js
src/components/MarketoForm/MarketoForm.js
src/hooks/useMarketoForm.js

When Firefox has "Strict" content blocked enabled, the developer site would crash because the browser removed `MktoForms2` from the `window` object. This PR checks to make sure it's available (and is loaded) before adding the form to the page.
I initially tried to create an _ErrorBoundary_ component, but the issue was coming from `gatsby-node` initially. At some point, we should consider building in some boundaries so the site can partially function in the event of errors.
* Closes #774 (issue)
* Closes #775 (first-pass attempt to solve the issue, thanks @curious-attempt-bunny !)

Fix Firefox crash (marketo forms)

---

src/announcements/dev-portal-vote.mdx

I'd prefer for us to put the nominee page, so we can show all the categories we've been nominated for. https://devportalawards.org/nominees/2020/new-relic

Swap out URL

---

package-lock.json
package.json

Bumps the theme to the latest version to implement a [fix](https://github.com/newrelic/gatsby-theme-newrelic/pull/111) to _AnnouncementBanner_ to help resolve an issue where banners weren't staying dismissed.
* Closes #779
* [https://github.com/newrelic/gatsby-theme-newrelic/pull/111](https://github.com/newrelic/gatsby-theme-newrelic/pull/111)

Fix for banners not staying dismissed

---

.github/workflows/fetch-related-content.yml

Updates the GitHub action, that triggers the updates to related content, to 
commit to `main` instead of `develop`. This ensures the site is redeployed when 
these changes occur without needing a team member to open a PR from `develop` to
`main`

Commit changes to related content on the main branch

---

src/markdown-pages/explore-docs/nerdstorage.mdx

there was an extra s on users' so I removed it based on this:
possessive singular: user's
possessive plural: users'

Removed extra s from users'

---

COMPONENT_GUIDE.md

Closes #853 
Updates the documentation on how to turn off the copy button. We had renamed the property from `copy` to `copyable` but forgot to update the documentation.

Update attribute name for toggling copy button

---

src/markdown-pages/build-apps/howto-use-nrone-table-components.mdx

Fixes a code block that has unnecessary trailing backticks in the commands

Remove unnecessary trailing backticks

---

gatsby-config.js

Make sure the default branch is specified as `develop` so that the edit links point to the proper place.

Add default branch to siteMetadata

---

src/markdown-pages/apis/index.mdx
src/markdown-pages/automate-workflows/diagnose-problems/error-alerts.mdx
src/markdown-pages/automate-workflows/diagnose-problems/index.mdx

- fixes the use of the old tip component in a couple guides. 
- fixes the "double" table on the API index page.

chore: fixed use of old tip component

---

package.json
yarn.lock

Fixes our component examples not rendering (i.e. [Button](developer.newrelic.com/components/button/?size=n_10_n)).
* Closes #1000

fix: revert bump to react-live to fix component examples

---

src/markdown-pages/automate-workflows/get-started-terraform.mdx

The page isn't using the proper capitalization for these vendors

Fix names of Slack and PagerDuty

---

package.json
yarn.lock

Similar work to https://github.com/newrelic/docs-website/pull/408 but with less resolutions.
`yarn audit` should return zero vulnerabilities.
* Closes #794

Resolved vulnerable dependencies

---

src/pages/index.js

current button directs to annemunition promotion from re:invent - need to update to the terraform guide.

update button for terraform guide

---

package.json
yarn.lock

This PR bumps the theme from [`v1.16.3` to `v1.18.1`](https://github.com/newrelic/gatsby-theme-newrelic/compare/v1.16.3...v1.18.1). Notable improvements include:
* `<SimpleFeedback />` component
* Terminal & Code Block improvements
* Simplified new issue flow
* Misc. adjustments / improvements

Update Theme Version

---

.github/stale.yml

This PR adds 2 new labels to the exempt list for stale bot so that new guides and sustaining issues don't get marked as stale.

chore: added new exempt labels

---

src/markdown-pages/explore-docs/query-and-store-data.mdx

this is currently pointing to https://developer.newrelic.com/intro-to-sdk which gives a 404 and I _think_ it should point to https://developer.newrelic.com/explore-docs/intro-to-sdk right?
PR to fix a currently broken link
Check [query and store data page](https://developer.newrelic.com/explore-docs/query-and-store-data) and link within page `guide to chart components` points to `/intro-to-sdk` but should be `/explore-docs/intro-to-sdk`
* for minor non-functional changes / additions to github …

Fixed broken link to chart components

---

src/markdown-pages/terraform/terragrunt-configuration.mdx

Fixed small typo on the terraform mini site

fix: typo changed "multple" to "multiple"

---

src/markdown-pages/build-apps/publish-deploy.mdx

This pull request adds a new section for showing users how to undeploying an app on New Relic.
It contains three steps:
- Get a list of subscribed deployed Nerdpacks for a New Relic account.
- Unsubscribe a particular Nerdpack ID from the account.
- Undeploy that Nerdpack ID.

chore:add instruction for undeploying an app

---

src/data/relicansData.js

Someone let me know that my social media information was incorrect on the Relicans page. Looks like my Twitter and Twitch usernames were swapped, so I've corrected them! No code changes, but you should now actually find me when you click on the Twitch and Twitter links from `/relicans`.

chore: fix social media links in relicansData

---

src/markdown-pages/automate-workflows/get-started-terraform.mdx

This PR bumps the version in the guide to the most current of our TF provider.

updated TF provider version to most current

---

src/pages/podcasts.js

Add Buzzsprout embeds for the other Relicans Podcasts
- https://twitter.com/LaunchiesShow
- https://twitter.com/PolyglotShow
On the [Podcasts page](https://developer.newrelic.com/podcasts) there should now be 3 embeds. Two listed above and the original Observy McObserveface

chore(podcasts): Add The Relicans Launchies and Polyglot podcast embeds

---

src/markdown-pages/build-apps/add-nerdgraphquery-guide.mdx
src/markdown-pages/build-apps/add-time-picker-guide.mdx
src/markdown-pages/build-apps/build-hello-world-app.mdx
src/markdown-pages/explore-docs/nr1-cli.mdx

Noticed a broken set-up-dev-env link
Also thinking we want to link to a different guide than is currently linked to in the nr1 cli guide (it links to the set up dev env guide for info on permissions. thinking we want the permissions guide)
Check out the 404 when clicking the "Set up your dev environment" link
https://developer.newrelic.com/build-apps/add-nerdgraphquery-guide
And the guide linked when clicking "Authentication and permissions"
https://developer.newrelic.com/explore-docs/nr1-cli

Fix guide links

---

src/pages/index.js

Updated the registration link for the FutureStack banner.
* [issue]()
```bash
```
* for minor …

chore: update registration link

---

src/pages/podcasts.js

We recently added Polyglot and Launchies podcasts to the site but didn't change the text that comes _before_ the podcast player embeds. Three paragraphs of the existing page content refer to only having a single podcast and therefore no longer make sense. I caught this as we were ending the stream where we made this change and would have forgotten to go back and fix it if not for @xomiamoore!
No code changes, but please do read the whole page and confirm it still makes sense?
* #1164

chore(podcasts): remove mentions of only having one podcast

---

src/data/relicansData.js

Update ChaelCodes' bio. The old one was no good.
At `/relicans` the bio for Rachael Wright-Munn should be updated to
"Rachael wants to share the joy and beauty of programming through programming games and regular open-source streams on Twitch. She's been a professional dev since 2012, 3x Team Lead, and manages an open-source repo for playing games of Monster of the Week. Currently, she works as a Developer Relations Engineer for New Relic."

Update ChaelCodes' Bio.

---

COMPONENT_GUIDE.md

- Minor language edits for Tutorial component guide
- Add "Things to keep in mind" section
One of these might be a bug, so let me know if I should create an issue for that.
* [issue]()
```bash
git commit -m "chore: …
```

chore: Update Tutorial how-to

---

STYLE_GUIDE.md

Adds info on how to use the `/embed` guide pages to the style guide.
Closes #1205

Add doc on embed guides to style guide

---

gatsby-config.js

Remove the i18 config from `gatsby-config.js` since this issue https://github.com/newrelic/gatsby-theme-newrelic/issues/302 has been resolved.

chore: remove i18 config

---

src/pages/index.js

This PR removes the Terraform CTAs and makes the home page all about Future Stack. As a note I commented out the registration button as that's a normal pattern we use, as the banner has the CTA to register in it.

chore: updated home page for future stack

---

src/markdown-pages/build-apps/create-an-ab-test-application/catalog-info.mdx
src/markdown-pages/build-apps/create-an-ab-test-application/chart-components-intro.mdx
src/markdown-pages/build-apps/create-an-ab-test-application/chart-group.mdx
src/markdown-pages/build-apps/create-an-ab-test-application/chart-headings.mdx
src/markdown-pages/build-apps/create-an-ab-test-application/confirmation-modal.mdx
src/markdown-pages/build-apps/create-an-ab-test-application/create-nerdpack.mdx
src/markdown-pages/build-apps/create-an-ab-test-application/demo-setup.mdx
src/markdown-pages/build-apps/create-an-ab-test-application/end-test.mdx
src/markdown-pages/build-apps/create-an-ab-test-application/first-chart.mdx
src/markdown-pages/build-apps/create-an-ab-test-application/grid.mdx
src/markdown-pages/build-apps/create-an-ab-test-application/index.mdx
src/markdown-pages/build-apps/create-an-ab-test-application/install-sdk.mdx
src/markdown-pages/build-apps/create-an-ab-test-application/navigation.mdx
src/markdown-pages/build-apps/create-an-ab-test-application/nerdstorage.mdx
src/markdown-pages/build-apps/create-an-ab-test-application/nerdstoragevault.mdx
src/markdown-pages/build-apps/create-an-ab-test-application/nrql-customizations.mdx
src/markdown-pages/build-apps/create-an-ab-test-application/nrql.mdx
src/markdown-pages/build-apps/create-an-ab-test-application/persist-selected-version.mdx
src/markdown-pages/build-apps/create-an-ab-test-application/pie-charts.mdx
src/markdown-pages/build-apps/create-an-ab-test-application/platform-state-context.mdx
src/markdown-pages/build-apps/create-an-ab-test-application/publish.mdx
src/markdown-pages/build-apps/create-an-ab-test-application/serve-app.mdx
src/markdown-pages/build-apps/create-an-ab-test-application/subscribe.mdx
src/markdown-pages/build-apps/create-an-ab-test-application/table-charts.mdx
src/markdown-pages/build-apps/create-an-ab-test-application/third-party-service.mdx
src/markdown-pages/build-apps/create-an-ab-test-application/user-interface-components-intro.mdx
src/markdown-pages/build-apps/create-an-ab-test-application/version-descriptions.mdx

Currently certain relative links are not working in embedded pages of the dev site. It seems like this has to do with the way the paths for the links were set up, though I don't actually know what about the `/embed` pages breaks this. It does seem however that supplying the full relative path works. This is also how we generally add links on the site so most pages should be okay. 
Check out one of the AB test app guides at the /embed url. Try following one of the first couple links. You should find that it links back to the site
Closes https://github.com/newrelic/developer-website/issues/1227

Update md links with full relative paths in AB guides

---

src/markdown-pages/build-apps/build-visualization.mdx

We've got a new field type for Visualization configuration fields. The CLI supports the new field type, but the UI doesn't yet so this PR is not quite ready to merge. Just getting into place for after we update the Custom Visualizations UI.
* [issue]()
* for …

Adds the new `account-id` type

---

package.json
yarn.lock

This PR bumps the theme which removes UTM params from the sign up button clicks, which should resolve some analytics problems.

chore: theme bump

---

src/markdown-pages/build-apps/serve-publish-subscribe/serve.mdx

The related resources job failed when it came across this url, changing it to the format we've been using
Make sure the nerdpack serve related resource still links to its page from the `/build-apps/publish-deploy/serve` guide

Adjust resource URL path in serve.mdx

---

gatsby-config.js

Updates the swiftype query filter on `type` to explicitly set which sites to get results from. This reduces noise from some of the site indexes and also avoids accidentally pulling in records for translated pages like `type: docs-jp`.
Closes https://github.com/newrelic/developer-website/issues/1264

[Related Resources] Update Swiftype query to only get results for specific sites

---

src/markdown-pages/explore-docs/custom-viz.mdx

One of the resource links on the custom viz doc had 2 slashes in the URL, which linked to a 404 page. This fixes that link + updates the other resources links to be relative to the root instead of the current page. This better futureproofs those URLS in case the location of the current viz page changes.

Fix an incorrect resource link. Use absolute URLs instead of relative

---

package.json
yarn.lock

The `gatsby-plugin-newrelic` dependency was not properly passing the referral field to segment. This updates to the newest version with a fix.
Partly closes https://github.com/newrelic/docs-website/issues/1816

fix: referrer field not being sent on sign up

---

src/markdown-pages/automate-workflows/diagnose-problems/error-alerts.mdx

This callout didn't have a `variant`.

chore: Fix broken callout

---

COMPONENT_GUIDE.md
src/markdown-pages/build-apps/create-an-ab-test-application/catalog-info.mdx
src/markdown-pages/build-apps/create-an-ab-test-application/chart-components-intro.mdx
src/markdown-pages/build-apps/create-an-ab-test-application/chart-group.mdx
src/markdown-pages/build-apps/create-an-ab-test-application/chart-headings.mdx
src/markdown-pages/build-apps/create-an-ab-test-application/confirmation-modal.mdx
src/markdown-pages/build-apps/create-an-ab-test-application/create-nerdpack.mdx
src/markdown-pages/build-apps/create-an-ab-test-application/demo-setup.mdx
src/markdown-pages/build-apps/create-an-ab-test-application/end-test.mdx
src/markdown-pages/build-apps/create-an-ab-test-application/first-chart.mdx
src/markdown-pages/build-apps/create-an-ab-test-application/grid.mdx
src/markdown-pages/build-apps/create-an-ab-test-application/index.mdx
src/markdown-pages/build-apps/create-an-ab-test-application/install-sdk.mdx
src/markdown-pages/build-apps/create-an-ab-test-application/navigation.mdx
src/markdown-pages/build-apps/create-an-ab-test-application/nerdstorage.mdx
src/markdown-pages/build-apps/create-an-ab-test-application/nerdstoragevault.mdx
src/markdown-pages/build-apps/create-an-ab-test-application/nrql-customizations.mdx
src/markdown-pages/build-apps/create-an-ab-test-application/nrql.mdx
src/markdown-pages/build-apps/create-an-ab-test-application/persist-selected-version.mdx
src/markdown-pages/build-apps/create-an-ab-test-application/pie-charts.mdx
src/markdown-pages/build-apps/create-an-ab-test-application/platform-state-context.mdx
src/markdown-pages/build-apps/create-an-ab-test-application/publish.mdx
src/markdown-pages/build-apps/create-an-ab-test-application/serve-app.mdx
src/markdown-pages/build-apps/create-an-ab-test-application/subscribe.mdx
src/markdown-pages/build-apps/create-an-ab-test-application/table-charts.mdx
src/markdown-pages/build-apps/create-an-ab-test-application/third-party-service.mdx
src/markdown-pages/build-apps/create-an-ab-test-application/user-interface-components-intro.mdx
src/markdown-pages/build-apps/create-an-ab-test-application/version-descriptions.mdx

Use the new "course" callouts instead of tips.
Here's what it looks like:

chore: Use new course callout

---

gatsby-config.js
gatsby-node.js
src/templates/GuideTemplate.js
src/templates/OverviewTemplate.js

Adds theme config option to force trailing slashes to try to make sure the sitemap includes trailing slashes to hopefully allow swiftype to index without encountering 302s.
- I _think_ this will close #1296

Force trailing slashes on page paths

---

gatsby-config.js
package.json
yarn.lock

To enable splits, AKA A/B testing, a new button component has been added to the theme's header. This PR updates to that version of the theme and sets up the required configuration values.
Related issue: https://github.com/newrelic/gatsby-theme-newrelic/issues/356

feat: Update theme to include split(a/b) testing

---

package.json
yarn.lock

Updates to 2.2.2 which includes a reduction in console warnings and whitespace wrapping in codeblocks

Update the gatsby theme

---

.github/workflows/fetch-related-content.yml

The current workflow enables branch protection with a required check for `checkout-and-build`, however, it's only triggered by pushes to develop and PRs from develop to main do not trigger that job. I have updated this to `Gatsby Build` which is the equivalent for PRs.

fix: enable branch protection with correct check

---

src/markdown-pages/build-apps/permission-manage-apps.mdx

Based on conversations, it's not true that basic users can use any non-FSO Nerdpacks. They can only use Nerdpacks that New Relic specifically permits basic users to use.

chore: Clarify what Nerdpacks basic users can use

---

src/data/observability-packs.json

Some fake data to get us started. This is grabbed from the future graphql endpoints and modified to include alerts for some of the packs. I also removed all dashboards and alerts from one of the packs to help with testing, since they are not required.
Closes #1331

chore: add o11y pack fake data

---

gatsby-config.js
package.json
src/data/observability-packs.json
yarn.lock

* pr to load data from observability-packs.json into graphql
* i also removed the top level field of observability-packs from the data since @roadlittledawn pointed out that produces an extra level of nesting in graphql that we dont need.
Resolves: #1332

1332 load data into graphql

---

CONTRIBUTING.md

This PR updates the section on the SDK bundle to offer more context of how we do updates to documentation as it relates to the SDK bundle from One Core.

chore: updated contributor guide

---

src/components/PackGrid.js
src/components/PackGridTile.js
src/components/PackList.js
src/components/PackListTile.js
src/pages/observability-packs.js

Added alternate List view for all packs which is responsive to view size
Changed the name of a couple of components to keep them in line with functionality:
`PackList` -> `PackGrid` (the list view uses `PackList` and vice-versa
`PackTile` -> `PackGridTile` (to differentiate from `PackListTile`

feat: pack list view

---

src/components/ImageGallery/ImageGallery.js
src/components/ImageGallery/index.js
src/templates/ObservabilityPackDetails.js

This PR adds an ImageGallery component for displaying images.
Aside from the visual organization, there is additional functionality:
* if passed no images, the component displays a single default image.
* each image is clickable and opens the full resolution image in a new tab.
You can see it in action on every observability pack page of the site. As an example: https://observabilitypacks-1341addimagegallery.gtsb.io/observability-packs/apache/QXBhY2hl/
Resolves: #1341

add image gallery component

---

src/components/Select.js
src/pages/observability-packs.js

Adds more responsive-ness to landing page, especially form controls / filters. Adds some custom form components for more control over styling and behavior. Very similar to those used in docs site's data dictionary page.
The grid view is already responsive.
* we may want to further refactor how filters work with state and URL params. i noticed that if you load a page with query params, the defaults are applied, then state is updated from query params.
Closes https://github.com/newrelic/developer-website/issues/1349
we may need to wait or merge the work for [list view](https://github.com/newrelic/developer-website/pull/1371) && [adding logos for featured images](https://github.com/newrelic/developer-website/pull/1372)

Make o11y pack landing more responsive

---

src/components/ImageGallery/ImageGallery.js
src/templates/ObservabilityPackDetails.js

Added some space in the header column for packs but otherwise things are looking good
**TODO**
Closes https://github.com/newrelic/developer-website/issues/1352
Tweaks https://github.com/newrelic/developer-website/issues/1341

O11y pack details mobile view

---

src/components/PackGrid.js

Adds a break point to reduce the grid to 3 columns instead of 4 at a certain width. Not sure if there are nicer ways to get this done with grid but it might do the trick
Closes https://github.com/newrelic/newrelic-observability-packs/issues/57

Add break point for o11y pack grid view

---

src/pages/observability-packs.js

`X` button now appears when there's a value in input, and clicking it clears the value
The `SearchInput` component requires `value` and `onClear` to be present to display the `X` button

fix: Search onClear functionality

---

src/components/ImageGallery/ImageGallery.js

This adds a fade to the right side of the image gallery to suggest there is more to scroll. I'm not sure if we want to add animation and get rid of the fade when you reach the last image 🤷‍♀️ but here's a first pass 🎉 
Closes https://github.com/newrelic/developer-website/issues/1385

Add fade to image gallery

---

src/markdown-pages/collect-data/collect-data-from-any-source.mdx

This PR deletes an unnecessary `the` article in a sentence.

chore: remove extra `the` article in docs sentence

---

src/markdown-pages/terraform/terrform-modules.mdx

Current instructions provide incorrect filenames
> First, inside of your HostModules directory, initialize a new Github repo. Add your module.tf and provider.tf to the stage for commit:
> 
> ```bash
> git add module.tf provider.tf
> git commit -m "init"
> ```
The file names in the directory should be `main.tf` and `provider.tf`

chore: update filename for module instructions

---

src/markdown-pages/build-apps/add-nerdgraphquery-guide.mdx
src/markdown-pages/build-apps/add-time-picker-guide.mdx

this PR fixes the discrepancies in a few code samples where we used  `PlatformState` instead of `platformState`

chore: fixes camel case inconsitencies

---

src/@newrelic/gatsby-theme-newrelic/icons/feather.js
src/components/ImageSlider.js
src/components/ImageSlider/ImageSlider.js
src/templates/ObservabilityPackDetails.js

Adds animated image slider and nav controls to go to next/prev/specific slides. Does not show nav controls if only one image. Assumes for now there will always be at least one image passed  in via props.
Wasn't sure what looked best for images either clipped on smaller screen or scaled down. Went with what I thought was slightly better option and scaled down image so you can see entire thing instead of tiny portion of it ¯\_(ツ)_/¯
Tried to address styling for nav controls being visible but obtrusive on both dark / light screenshots.
Related to:
- https://github.com/newrelic/developer-website/issues/1405
- https://github.com/newrelic/developer-website/issues/1388
- https://github.com/newrelic/developer-website/pull/1415 (incorporated most of @zstix feedback from this PR into this one) …

Add animated image slider

---

STYLE_GUIDE.md
src/templates/ObservabilityPackDetails.js

This PR changes the dependency tab to requirements per feedback from the UX Team.

chore: changed name to requirements

---

package.json
scripts/actions/fetch-observability-packs.js

We were using the environment variable `CI` to determine if a script was executed directly or imported for tests. However, Github Actions force sets that variable to `true`, so it will also be true when we're trying to run unit tests in a job. 
This PR removes that environment variable and transfers to using `require.main === module` to determine how the file is being accessed. [Node docs on `require.main`](https://nodejs.org/docs/latest/api/modules.html#modules_accessing_the_main_module)

fix: swap CI env variable for require.main

---

src/pages/observability-packs.js
src/templates/ObservabilityPackDetails.js

This PR changes applications to nerdpacks in the filter and removes "checks" from Synthetics in the filter and tabs

chore: changed application to nerdpack

---

gatsby-config.js

There's an issue with the `Transform data` example of the NrqlQueries component in our [sdk docs](https://developer.newrelic.com/components/nrql-queries/), this issue isn't present in the internal sdk docs site so I'm rolling us back to the version of the sdk they currently use

Use most recently stable version of SDK

---

CONTRIBUTING.md

This updates the contributing doc with an SDK version source that is easier to troubleshoot (the version used by the live one-core site)

Update SDK documentation

---

src/pages/observability-packs.js
src/templates/ObservabilityPackDetails.js

Moves the search input to the filters area. Animates expanding / collapsing the input on button click.
Adds keyboard shortcut `s` to expand search.
Adds tessen/browser page action tracking for search button clicks.
Wasn't quite sure if I should expand on mobile by default.
* Closes https://github.com/newrelic/developer-website/issues/1459
https://user-images.githubusercontent.com/2952843/124802491-e20c7180-df0c-11eb-9f86-54f4c1a54498.mp4

Move search to filters area

---

package.json
src/components/CodeDef/Comment.js
src/components/MethodReference.js
src/components/PropList.js
src/templates/ApiReferenceTemplate.js
src/templates/ComponentReferenceTemplate.js
src/templates/ObservabilityPackDetails.js
yarn.lock

Adds markdown support for pack description content on the pack details page.
Includes updating to latest version of `react-markdown` and some small updates for breaking changes. Far as I could tell rest of site looked okay (esp the SDK area of the site) but would love second set of 👀 
I used [this sample markdown string](https://gist.githubusercontent.com/roadlittledawn/26fb5b622a4b49167838e0793b3d4269/raw/3f091437f33188db9b252a0545ead5b019a55be2/sample-description.md) to test rendering and what was allowed / disallowed by adding it to a pack `description` field in `src/data/observability-packs.json`.
Closes https://github.com/newrelic/developer-website/issues/1462

Support markdown for pack descriptions

---

src/components/PageLayout/PageLayout.js
src/components/Tabs/Bar.js
src/components/Tabs/BarItem.js
src/templates/ObservabilityPackDetails.js

This removes the requirements and nerdpacks tabs from the observability pack details page, and mocks the requirements info in the right rail. I also adjusted some mobile styles to avoid a scroll bar on the tabs as much as possible
Closes https://github.com/newrelic/developer-website/issues/1434

Reduce number of tabs in observability pack details

---

src/components/Tabs/Bar.js

Checks if mobile device is iOS and if so adjusts to text color in the select to be more readable on the gray background
Closes https://github.com/newrelic/developer-website/issues/1421

Change tab select styling on ios browsers

---

plugins/gatsby-source-newrelic-sdk/gatsby-ssr.js
src/components/PackImg.js
src/components/PackTile.js
src/templates/ObservabilityPackDetails.js

This adds an image component which will conditionally render a supplied logo image or a placeholder.
I took some creative liberty and referenced the stripes from the site logo but am open to any design!
TODO:
Closes https://github.com/newrelic/developer-website/issues/1428

Add a default logo for packs without an image

---

src/templates/ObservabilityPackDetails.js

Adds section in `PageTools` for support level and copy.  We can safely assume we will one of the 3 since it's validated via a workflow in the observability packs repo.
For now I thought it made most sense to keep the data (`title` and `content`) in the same file so it's easy to find / update for content contributors.
Closes https://github.com/newrelic/developer-website/issues/1408

Add section for pack support level and copy

---

src/components/PackImg.js
src/components/PackTile.js
src/images/build-your-own.svg
src/images/default-logo-background.svg
src/pages/observability-packs.js

This PR is for adding a tile to the observability pack list that links to the pack repo to encourage folks to build their own
TODO
This issue is mainly stemming from the fact that the tile needs to externally link and is currently built for internal links
Closes https://github.com/newrelic/developer-website/issues/1481

Add build your own pack tile

---

src/pages/students.js

There seems to be a wrong registration link on the Student GitHub Education Pack page. I do not know if it should be corrected to the general one I added, but it certainly should not be this form on Google. 
Also recently, I noticed that the broken option that should allow verification with a GitHub account has disappeared from the New Relic One panel. Can you still get the New Relic GitHub Education Pack?
I tried to contact the email provided on GitHub Education Pack page but no one has been writing back for over a month. However, if this promotion is over, it might be better to remove this article.
If there are any related [GitHub Issues](https://github.com/newrelic/developer-website/issues) or JIRA tickets, add links …

chore: fix signup link on student page

---

src/templates/ObservabilityPackDetails.js

- Closes #1482 
- Delete Visualization and Synthetics tabs from `ObservabilityPackDetails.js`
- Deletes functions that define rendering Visualization and Synthetics tabs

Delete vis and syn tabs from ObservabilityPackDetails.js

---

src/components/InstallButton.js
src/data/constants.js
src/templates/ObservabilityPackDetails.js
src/utils/get-pack-nr1-url.js

Connects the `Install Pack` button to the login page so that the user is redirected to our installation nerdlet. The `packId` is included in the URL so that the user will see the details for the right observability pack when they get into the platform.
The following user flows work:
1. As a user that is logged in, click on `Install Pack` on the details page.
2. You will be taken right to the installation nerdlet.
1. As a user that is logged out, click on `Install Pack` on the details page.
2. Log into New Relic.
3. On successful login, you will be taken to the installation nerdlet.
The following user flow currently does _not_ work:
1. As a new user that does not have an account, click on `Install Pack` on the details page.
2. Create a new account.
3. Verify your account email.
4. Login …

Connect Install Button to Nerdlet in NR1

---

src/components/InstallButton.js
src/data/constants.js

Switches install button links on pack details pages to point to staging-one.newrelic.com by default instead of using dev and using locally running nerdpack.

Switch install links to nr1 staging

---

src/pages/futurehack-2021.js

This (temporarily) adds a cookie on load of the futurehack page. We want to test out the use of a cookie to pass pack information to one.newrelic for installs as outlined here https://github.com/newrelic/newrelic-observability-packs/issues/127

Add temporary test cookie

---

src/templates/ObservabilityPackDetails.js

Adds a data source tab and page with empty state
Closes https://github.com/newrelic/developer-website/issues/1511

Add data sources tab

---

gatsby-config.js
package.json
yarn.lock

Adds config option for gatsby cloud plugin to change referrer-policy from `same-origin` to `strict-origin`.
Partially addresses https://github.com/newrelic/gatsby-theme-newrelic/issues/437

Change referrer policy to expose referrer for external link clicks

---

scripts/actions/fetch-observability-packs.js
src/data/observability-packs.json

Added alerts to the GraphQL query and removed unneccesasary filter options. The following are no longer on the roadmap for initial GA:
-'Visualizations',
-'Synthetics',
-'Nerdpacks',

chore: reduce filter options

---

src/data/constants.js
src/utils/get-pack-nr1-url.js

This PR works in tandem with the refactor PR of the nerdlet. Changing the packId provided in the nr1 url to quickstartId in the dev site and consuming quickstartId in the nerdlet

Rename packId to quickstartId in install url

---

src/pages/observability-packs.js

Draft PR for now until we figure out if we want submit button OR some other logic on auto searching.
This updates the text input and two filters to update and navigate (using @reach/router) via query params so it's added to browser history and a user can go forward / backward in history.
https://github.com/newrelic/developer-website/issues/1475
TBD

Search o11y packs by navigating via query params

---

src/markdown-pages/automate-workflows/get-started-new-relic-cli.mdx

`newrelic profile add` no longer recognizes the `-n` shorthand flag. The correct and current syntax should be `newrelic profile add --profile <string>`
Updating the flags for the current version of newrelic-cli 
* [issue]()
* for minor non-functional changes / …

newrelic profile add -n > --profile

---

src/components/Breadcrumbs.js
src/templates/QuickstartDetails.js

Adds a `Breadcrumbs` component and uses it on the pack details pages above the page title / pack name.
Stopped short of adding to theme for time being, but made it its own component so it's a wee bit easier to port over if/when we want to.
Closes https://github.com/newrelic/developer-website/issues/1559

Add breadcrumbs to details pages

---

src/components/quickstarts/OverviewTile.js
src/components/quickstarts/QuickstartOverview.js
src/templates/QuickstartDetails.js

Changing overview layout to display grid tiles. Each tile is one supplied component from the quickstart (1 dashboard, 1 alert, etc). For dashboards, an image is displayed. For alerts and documentation, the description is displayed & truncated to 250 characters.
Everything: https://build-e45a3b32-2eb0-4594-8c91-6d9e5f1bb56b.gtsb.io/instant-observability/elasticsearch/RWxhc3RpY3NlYXJjaA==
Desktop:
Mobile:
Closes: #1555

Switch overview layout to display quickstart content tiles

---

src/components/DevSiteSeo.js
src/components/FunctionDefinition.js
src/components/MethodReference.js

This PR adds a few fixes to reduce the number of errors on the developer site. More specifically, this removes:
* The warning that we needed a unique `key` for the `<meta>` tags coming from our SEO component
* The warning coming from the `logger` API page (due to the SDK being in a weird state - see screenshots)
It looks like the SDK for the `logger` API is mostly incomplete. A number of the adjustments in the PR were defensive adjustments to get the page to render without errors. That said, it's still pretty incomplete:

Fix `logger` API page

---

src/components/Breadcrumbs.js
src/components/Tabs/Page.js
src/layouts/QuickStartLayout.js
src/pages/instant-observability.js
src/templates/QuickstartDetails.js

I noticed a few design inconsistencies when compared to the designs and the in-product experience. I wanted to start addressing those as we get closer to GA. Some of the changes include:
* Adding the description below the quickstart title (like the in-product catalot)
* Adding the logo on the quickstart detail page (like the in-product catalog)
* Adding a background to the breadcrumb bar (like the designs)
* Tweaks to spacing / fonts to match the designs
* Simplifying some of the DOM (we had a few extra `<div>`s that were unnecessary)

Design Tweaks

---

src/utils/get-pack-nr1-url.js

We were adding `/nerdlet/catalog-pack-details.catalog-pack-contents` to the nr1 url when installing a pack. i don't think it's possible to load a nerdlet this way and it seems it redirects for some users and not others. This removes that part of the url (but maintains the nerdlet ID passed in the pane param) which uses the platform to launch our nerdlet. if we don't want to see the platform tabs at the top (explorer, alerts, etc) we can make our own launcher, but in the meantime this will at least render things functional

Remove /nerdlet from nr1 url

---

src/components/PackTile.js
src/components/Tabs/BarItem.js
src/pages/instant-observability.js
src/templates/QuickstartDetails.js

Tessen requires that event names be `camelCase` and category to be `TitleCase`. If they're not, events do not report / fail silently. Some of these events were not sending until I changed the format. I confirmed that all instrumented events sent when running locally.
I also updated the event names to use one standard name. That makes it easier to query downstream when Tessen packages up events for segment and NR1.
Partially addresses https://github.com/newrelic/developer-website/issues/1603
We don't quite seem to stick to a standard for tessen event naming. But generally, it seems `eventName` is the more broad of the two and `category` is a specific type of said event.
Our tessen wrapper uses this signature:
```
Tessen.track("eventName", "CategoryOfThing", {…})
```
Which packages that …

Update tessen naming for required format, consistency

---

src/templates/QuickstartDetails.js

The component that renders the description markdown was removed during a redesign. This PR just re-adds it.

fix: add markdown description back

---

src/pages/futurehack-2021.js

Now that we've confirmed a cookie approach for quickstarts we can remove this test cookie

Remove test cookie

---

src/pages/instant-observability.js

Changes the `category` property name to avoid conflicting with the Tessen `category` which overwrites this property when it's sent to segment. In this case, the `category` that's used is `QuickstartCatalogSearch`.

Update tessen QuickstartCatalogSearch event property to avoid name conflict

---

src/@newrelic/gatsby-theme-newrelic/components/Logo.js
src/layouts/QuickStartLayout.js

this is _a_ solution, not sure if it's _the_ solution. because it's an SSR issue i wasn't sure of a solution that doesn't involve the developer icon flashing in the footer (but you would have to be scrolled to the bottom and refresh to see it), same with the footer width/icon in the details view (scroll to the bottom and refresh to see)

Add useEffect and state to conditionally render footer width/logo

---

src/components/InstallButton.js
src/data/constants.js
src/utils/get-pack-nr1-url.js

This PR sends the user to the guided install flow if the quickstart has a guided-install installPack only. Else the user is sent to the catalog-pack-contents nerdlet as before.
* [issue]()
* for minor non-functional changes / additions to github actions, …

Send user to guided install nerdlet

---

gatsby-config.js
package.json
src/layouts/MainLayout.js
yarn.lock

This removes the `CookieConsentDialog` component from the main layout in favor of OneTrust.
Also bumps theme version for tessen amplitude setting.
We'll likely have to update the theme's tracking code (tessen, ga) to no longer check the cookie set by this component before firing analytics calls.
Related to:
* https://github.com/newrelic/developer-website/pull/1656
* https://github.com/newrelic/gatsby-theme-newrelic/pull/463

Remove CookieConsentDialog in favor of OneTrust

---

src/pages/instant-observability.js

I noticed some small differences between the internal marketplace and our catalog. Specifically the ordering and which terms the search compares. 
* quickstarts are now sorted alphanumerically by the title field
* catalog search now compares against title instead of name, to align
with the internal catalog.
* catalog search now includes summary

Catalog ordering and search updates

---

gatsby-config.js

Adds `*.skilljar.com` to the list of domains allowed to embed developer site content

fix: add skilljar as an iframe-able domain

---

gatsby-config.js
src/layouts/MainLayout.js

David Hwang said we should be okay to deploy so re-adding OneTrust and removing custom cookie component.
Related to:
* https://github.com/newrelic/developer-website/pull/1668
* https://github.com/newrelic/developer-website/pull/1656
* https://github.com/newrelic/gatsby-theme-newrelic/pull/463

Re-add OneTrust

---

scripts/list-quickstart-urls.js

The previous check only worked if there was a single install plan, but some packs have multiple. this checks for any packs with any number of install plans

Fix url list script

---

gatsby-config.js
package.json
src/layouts/MainLayout.js
yarn.lock

Bumps theme to latest version just released to fully switch over to new cookie mgmt / tessen upgrade.
This _should_ enable us to report tessen data from preview builds

Use latest theme for new cookie mgmt / tessen upgrade

---

src/components/IOBanner.js

The banner text was expanding on larger screen to break out of the background image. This adjusts the text to a fixed size to prevent this from happening.
* Closes #1701

fix banner text breaking out of image

---

src/components/InstallButton.js

fix: remove extra encoding step

---

src/components/InstallButton.js

We were linking directly to the `/login` page, but we actually want to link directly into nr1 and let the auth flow handle logging in. This does not affect the behavior when a UTM parameter is added.
Closes #1727

fix: link directly to nr1 instead of login page

---

src/components/InstallButton.js
src/templates/QuickstartDetails.js

Moved tessen.track for the Install Button into the InstallButton.js. Added  a field to tessen to check the button text when clicked. 
Closes https://github.com/newrelic/developer-website/issues/1733

chore: add quickstartbuttontext field to tessen

---

src/templates/QuickstartDetails.js

* reorganized the header to have logo on the left, title & summary in
the middle, and CTA buttons on the right
* header is sticky and will remain on page when a user scrolls. it
will 'stack' up  with the global header which is also sticky
Resolves: #1800

make quickstart header sticky

---

src/components/InstallButton.js

* when a user visits a quickstart page directly, or reloads a page,
the install button links to signup, despite ajs_user_id existing. With
this change, we force the page to re-render to have the correct url --
if they have the cookie set.
Resolves: #1865

fix: fix for install button having signup as link too often

---

src/components/PackTile.js

These were looking a little rough in dark-mode (see before / after screenshots in the pull request). This isn't a perfect solution, but I think it looks much better than before.
**BEFORE**
**AFTER**
*

Add background for quickstarts in dark mode

---

src/data/nav.yml

This PR fixes the names of the feather icons in the nav.yml file to not trigger the console warnings.

chore: fixed feather icons

---

src/components/DevSiteSeo.js

This PR attempts to add the crazy egg script to the developer site home page as well, so both the `/` page an `/instant-observability/` both have the script running.

chore: added script to dev site home

---

src/components/InstallButton.js

The original spec for the cookie was generic and not specific to NRIO or Quickstarts. We need to move towards the generic approach to move in line with architectural guidance, remove special cases in repositories, and improve analytics.
This is the first of multiple steps to move us towards that generic cookie `start_target`.
I'm going to go step-wise:
1. Update here
2. Update in guided-install's router which reads the cookie and sends you to the appropriate location
3. Return here and remove `newrelic-quickstart-id` unless it's being used elsewhere
Reviewer should only need verify writing the cookie succeeds
* [issue]() …

fix: Update cookie to match original spec

---

COMPONENT_GUIDE.md

Add documentation and usage examples for the super tiles experiment (A/B test) that was [merged earlier today](https://github.com/newrelic/developer-website/pull/1887).
There is a new section called _Experiments_ that we might be able to make use of in the future if there will be more.
* [[Dev Site] Document new super tile component](https://github.com/newrelic/developer-website/issues/1890)

chore(docs): add docs for super tiles experiment components

---

src/experiments/super_tiles/components/GuidedInstallTile.js

Looks like `navigate()` prevents Tessen from registering that event if it happens at the same time as `tessen.track`. Using `useInstrumentHandler` is a better approach compared to using timeouts.

fix: tessen event not triggered on click for guided install tile

---

.prettierrc.js
gatsby-config.js
package.json
src/components/IOBanner.js
src/components/InstallButton.js
src/components/PackTile.js
src/components/quickstarts/QuickstartDataSources.js
src/pages/instant-observability.js
src/templates/QuickstartDetails.js
yarn.lock

* Bring in latest version of the theme
* Update usage of instrumentation to only use tessen -- no longer use pageAction
* Update usage of tessen since latest version of theme has function signature changes
* Additionally, bringing in latest of theme also brings in anonymousId tracking to each tessen call
Relates to: #1885

updates to use only tessen

---

src/pages/instant-observability.js

Resolves gatsby cloud build error

chore: remove iconUrl from query

---

src/experiments/super_tiles/components/GuidedInstallTile.js

Let's redirect to the login page instead of always going to sign up for the guided install super tile A/B test if there is a 🍪  present.

refactor: redirect to login instead of sign up if cookie exists

---

gatsby-config.js

- Updated the SDK version to `release-3439`
- I did not find any new components to add this time. 
- I did a local build and poked around a little on the SDK pages and everything seemed okay. 
Closes https://github.com/newrelic/developer-website/issues/1933

chore: update sdk version

---

src/components/InstallButton.js

We have functionality to not display the `install`/`See documentation` button if the quickstart has neither an installable component or any other component (dashboard/alert/documentation), but because of where it was in the component it wasn't being returned in time. We were defaulting to `quickstarts.documentation[0].url` for the URL of the install button before verifying that the quickstart had a documentation reference

fix: failure on no docs and no install plan

---

src/markdown-pages/terms.mdx

Some minor adjustments to the headers 
- Sometimes `**Header.**` instead of `**Header**.` is being used - this is causing the `ReactMarkdown` parser to split the header by the `<strong>` element (which is a `display: block;` by default) but leaves the content (the `<p>` element) on a separate line along with the period.
**Example:**
- `**"you**"` is being used vs. `"**you**"`

chore: minor terms.mdx formatting adjustments

---

src/components/InstallButton.js

With the completion of some work around using `start_target` instead of `newrelic-quickstart-id` this PR cleans up its usage. It's no longer needed. 
1. Click on an NRIO tile
2. Ensure you land on the Catalog Pack Details page for that NRIO tile
* [JIRA Ticket](https://newrelic.atlassian.net/browse/VIRTUOSO-1554)
* for minor …

fix: Cleanup and remove newrelic-quickstart-id

---

src/markdown-pages/explore-docs/nr1-cli.mdx

The app catalog is on its way to be deprecated and is no longer the place to find the build your own tile, this updates the guide on this
closes https://github.com/newrelic/developer-website/issues/2021

Update dev center launcher location in doc

---

src/components/GuideTile/GuideTile.js
src/templates/LabOverviewTemplate.js

Task from Alex Ronquillo from New Relic org. Purpose of this is making new styles for lab procedures while we have parrarel sub  procedures.
For testing it you have to make procedure with not-integer ProdIdx, example: ProcIdx 2.1, should be under ProcIdx 2 with simpler styles.

feat: new styles for subtask in lab

---

.github/workflows/release.yml

change-log check was failing going to `main` needed version 16 of node

fix: update node version for change-log

---

src/data/nav.yml
src/pages/index.js

Getting hardcoded urls that redirect to the new I/O site changed to the actual url.  This was throwing a 404 error when trying to click on these buttons in prod.

URL updates for I/O site

---

src/data/nav.yml

We deleted events page from developers navigation  because it is outdated, if we will have any updates we can just restore that to nav.
* [Deprecate the events page](https://github.com/newrelic/developer-website/issues/1891)
```bash
git commit -m "chore: adjusting config and …
```

Remove the event page from navigation

---

src/markdown-pages/automate-workflows/get-started-terraform.mdx

Updated the Terraform version information, so customers use the latest version.

fix: updated terraform version information

---

src/markdown-pages/explore-docs/custom-viz/configuration-options.mdx

Customers creating custom visualizations that don't follow our recommended way because it was never mentioned in the docs, so we decided to add this recommendation.
- checkout the branch
- `npm i && npm start`
- navigate to http://localhost:8000/explore-docs/custom-viz/configuration-options#nrql
- verify that new warning callout is added
- [[Docs] Review and update Custom Visualizations public docs](https://issues.newrelic.com/browse/NR-23110)

fix(custom-viz): Add recommended way of using nrql property

---

src/markdown-pages/contribute-to-quickstarts/build-a-quickstart/create-quickstart.mdx

Fixing link to conventional commits in developer contribution docs. 
https://github.com/newrelic/developer-website/blob/main/CONTRIBUTING.md#using-conventional-commits
```bash
```
* for minor functional corrections to code.
```bash
git commit -m "fix: typo and prop error in the code of conduct"
```
* for major functional changes or …

fix: update link to conventional commit in docs

---

src/markdown-pages/automate-workflows/get-started-terraform.mdx

Alerts channels are legacy and are being replaced by notifications destinations & channels.
* Notifications destination terraform [link](https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/resources/notification_destination)
* Notifications channels terraform [link](https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/resources/notification_channel)
* [Jira](https://issues.newrelic.com/browse/NR-38488)
* …

chore(terraform): Replace alerts channels with notifications destinations & channels

---

gatsby-config.js
package.json
src/@newrelic/gatsby-theme-newrelic/components/Logo.js
src/__generated__/gatsby-schema.graphql
src/__generated__/gatsby-types.d.ts
src/layouts/MainLayout.js
yarn.lock

Theme bump to get the developer site up to date with the theme, added styles to make the side nav look the same as that of the docs site.

Tabatha/theme bump 6.13.7

---

gatsby-config.js

Part of the work to remove Split IO configs from all our Gatsby sites.

Remove Split I/O config

---

src/markdown-pages/automate-workflows/get-started-pulumi.mdx
src/markdown-pages/pulumi/get-started-pulumi.mdx

This change just updates a couple of links in the Pulumi documentation -- one to point to the Pulumi home page instead of docs (a better link for more general info), the other to link to the Pulumi Service (easier access for the those who are interested).
None.
Closes https://github.com/pulumi/devrel-team/issues/110.
None.

[chore] Update links to Pulumi, Pulumi Service

---

src/components/ReferencePreview.js

This makes labels in sdk component doc previews a light color when in dark mode (check out the TextField component for an example)

Make sdk label dark mode responsive

---

src/markdown-pages/automate-workflows/get-started-pulumi.mdx
src/markdown-pages/pulumi/get-started-pulumi.mdx

This change updates the Pulumi getting-started guide to use the recommended set of New Relic provider resources. (The guide is currently broken; this change fixes it.) 
Thanks @ptahdunbar for the assist!
None.
Closes https://github.com/pulumi/devrel-team/issues/469.

[chore] Update Pulumi getting-started guide

---

src/markdown-pages/contribute-to-quickstarts/build-a-quickstart/add-data-source.mdx
src/markdown-pages/contribute-to-quickstarts/build-a-quickstart/understand-quickstart.mdx

Updates for data sources:
* `install/` will be removed and use of install plans deprecated

Update quickstart guide with changes for data sources and install plans

---

src/markdown-pages/automate-workflows/automated-tagging.mdx

This PR updates the documentation to match the new Entity header. It is related to [another PR](https://github.com/newrelic/docs-website/pull/13937) on the `docs-website`.
I noticed some things while making these changes, which can be improved upon:
- The screenshots in the [section](https://developer.newrelic.com/automate-workflows/automated-tagging/#check-your-tags) are outdated. I searched for the app mentioned (hello-app-1), to update the screenshot, but wasn't able to find it.
- The search redirect link in the first line does not work as expected anymore.
- The metadata widget could be independent or might show up inside the '...' button (refer screenshots below).
If there are any related [GitHub Issues](https://github.com/newrelic/developer-website/issues) or JIRA tickets, add links …

chore(EntityHeader): Update documentation for the new Entity header

---

src/markdown-pages/pulumi/get-started-pulumi.mdx

By pointing the user to use `pulumi config` instead of env vars, it demonstrates both stack config and Pulumi's encryption of secrets by default, which is one of its more compelling features.
* [issue]()
* for minor non-functional changes / additions to github …

Modify Pulumi instructions to use pulumi config instead of env vars.

---

src/markdown-pages/opentelemetry-masterclass/hands-on/workshop-dotnet.mdx

Until we can update this tutorial, users will need to install these exact versions of dotnet packages to run it.
Previously, the instructions for installing dependencies used the `pre-release` flag; however, the versions of the dotnet packages installed with the flag will cause the tutorial to break. 
This is a temporary fix until we either update or replace the material.

Modify install instructions
