newrelic/developer-website

src/pages/index.js

added marks video
https://newrelic.atlassian.net/browse/DEVEX-1045

added marks site walkthru video

---

src/components/FeatherIcon.js
src/components/SearchInput.js
src/components/SearchInput.module.scss

Closes #336
Center-aligns the search and clear icon in the search input.

Center align the search input icon

---

src/components/Seo.js

This field identifies the source site for each record in the swiftype index. It’s used to filter results to a specific website.
* [issue]()

Add meta tag for swiftype type field for every page

---

src/data/sidenav.json

Updated the left nav under automate workflows to be a bit more intuitive.
If there are any related [GitHub Issues](https://github.com/newrelic/developer-website/issues) 
* [issue](https://github.com/newrelic/developer-website/issues/351)

Issue #351 - reorder left nav under automate workflows

---

STYLE_GUIDE.md
src/markdown-pages/explore-docs/intro-to-sdk.mdx

- Fixed  a redirect from the old dev site 
- updated style guide with redirect frontmatter info
N/A
https://github.com/newrelic/developer-website/issues/358

Page redirect change

---

src/markdown-pages/explore-docs/intro-to-sdk.mdx

fixed redirect route to actually work this time.
N/A

fixed redirect route

---

src/markdown-pages/automate-workflows/get-started-new-relic-cli.mdx

Fix for this issue - https://github.com/newrelic/developer-website/issues/381
* [issue]()

fixing link - issue 381

---

CONTRIBUTING.md

Documented in the Contributor guide how to submit a draft PR.
https://github.com/newrelic/developer-website/issues/379

Documenting Draft PR process

---

src/markdown-pages/automate-workflows/index.mdx

we had some feedback that a google search led to a 404. redirected that page.
* [issue]()

Added a redirect from the previous site.

---

README.md

To comply with the open source checklist, I added an NR discuss topic to readme
n/a
https://github.com/newrelic/developer-website/issues/309

added a NR discuss topic to readme

---

gatsby-config.js
package-lock.json
package.json

This PR adds the gatsby google analytics plugin
#394

chore: Add google analytics

---

src/markdown-pages/explore-docs/intro-to-sdk.mdx

Updates the invalid `<NerdletStateContext />` URL and the `api` URLs. Also uses URLs relative to the root rather than the current route.

Update invalid URLs + use relative URLs relative to the root

---

src/markdown-pages/explore-docs/nr1-cli.mdx

saw a few typos, so I fixed them.
n/a
n/a
n/a

fixed typos in cli docs

---

package-lock.json
package.json

Installs the needed semantic release packages that are missing and causing our
release action to fail.

Install needed semantic release packages

---

.github/workflows/release.yml

Closes #304 
Adds the necessary jobs to the release action to generate the third party notices automatically.

chore: add jobs for generating third party manifest file

---

.github/workflows/release.yml
.releaserc
amplify.yml
src/components/Footer.js
src/components/GlobalHeader.js

Renaming all the references to master to main

Renaming all references of master to main 

---

src/components/__tests__/__snapshots__/Footer.js.snap
src/markdown-pages/explore-docs/intro-to-sdk.mdx

added a link to nerdpack layout repos.
n/a
n/a
n/a

added a link to nerdpack layout repos

---

src/markdown-pages/build-apps/add-nerdgraphquery-guide.mdx
src/markdown-pages/build-apps/build-hello-world-app.mdx

I made changes to make the  **Before you begin** steps closer to those in the time picker and nerdgraphquery topics. 
This revamp includes a reference to the Node installation. Also, the steps are slightly different from the time picker and nerdgraphquery steps:
* User need to complete all the steps of the CLI wizard (and the rest of the doc makes that assumption.
* Users don't need to do anything with the account ID for the Hello World exercise.

Hello World: Environment setup step improvements

---

src/markdown-pages/build-apps/add-nerdgraphquery-guide.mdx

I made the **Before you begin** section identical to the time picker guide (pull request #398).
Here are some things to check:
* The new section for **Before you begin** should have a link to the Node installation, as well as a link at the end to the environment setup page on the development site.
* I inserted a few colons at the ends of sentences that introduced images.

Nerdgraphquery guide: Improvements for **Before you begin**

---

src/components/NavigationItems.js
src/components/NavigationItems.module.scss

This PR adds toggling to the component library nav item, and also fixes a bug in which refreshing causes the subnav to collapse
Check out the Component library nav item in Explore docs in the PR build
Partially addresses #433

chore: Add toggle to component library

---

src/data/sidenav.json
src/markdown-pages/automate-workflows/get-started-kubernetes.mdx

Add a getting started guide for the New Relic Kubernetes operator.
Resolves newrelic/developer-toolkit#28.

docs: add a getting started guide for the NR k8s operator

---

src/markdown-pages/automate-workflows/get-started-kubernetes.mdx
src/markdown-pages/build-apps/build-hello-world-app.mdx
src/markdown-pages/build-apps/set-up-dev-env.mdx

This commit adds a note about forking to the setup dev env doc, edits a tiny thing on Hello World doc, and removes the step element from around "What's next?" on the k8 doc.
* [issue]()

Couple of fixes to setup dev env page, and edits to two other files

---

src/markdown-pages/build-apps/add-time-picker-guide.mdx

fixed broken url
saw the url in this important call out was broken.
n.a
n.a
n.a

fixed broken url

---

src/data/sidenav.json

Added left nav link to apps page

---

src/components/Seo.js

closes #354 
Adds metatags for the developer site so swiftype can have fun crawling our pages!

Swiftype metatags for developer site

---

src/pages/index.js

Updates to the index page copy / button.

Index Page Context Updates

---

package-lock.json
package.json
src/components/Footer.js
src/components/MobileHeader.js
src/components/PageLayout/RelatedContent.js
src/components/Sidebar.js
src/layouts/MainLayout.js

Tell Swiftype to stop indexing our footer, related content area, and sidebar navigation. Tell Swiftype the body content area.

Tweak indexing

---

src/data/sidenav.json

Hoping this will build the build.
* [issue]()

Fixed a typo on Cli docs nav

---

CONTRIBUTING.md

link ref was 404'ing on GH so I fixed it.

fixed link ref to sidenav.json

---

src/components/NavigationItems.js

This PR makes the new `New Relic One CLI` sub nav toggle-able

Add nav item toggle to New Relic One CLI

---

src/data/sidenav.json

Removed extra wordiness in the sidebar

---

src/components/RelatedContentModules/Swiftype.js
src/components/relatedQueries.js

Add test cases to use tags to drive the related content

Use tagging to drive related content

---

src/components/relatedQueries.js

Adds a query including the title and the description, search it all!
Closes #553

Add title + description query

---

package-lock.json
package.json
src/components/styles.scss
src/layouts/MainLayout.js
src/pages/404.js

This PR adds a global search to the global header
Closes #474

Add search to global header

---

src/components/relatedQueries.js

This PR adds two queries that match on the title and weight results based on matching titles/bodies
Closes #564

Add queries for title with weighted results

---

gatsby-node.js
package-lock.json
package.json
src/components/RelatedContentModules/Swiftype.js
src/components/relatedQueries.js

Latent Dirichlet allocation is a natural language processing technique to find groups of related words. You can read a little bit more about this [here](https://en.wikipedia.org/wiki/Latent_Dirichlet_allocation). I used a Node.js library to run analysis on the body of each document, find the most relevant terms, and then I use those as search queries.

Research with LDA tagging method

---

gatsby-node.js
src/components/RelatedContentModules/Resources.js
src/templates/GuideTemplate.js

Closes #580 
Adds related resources from Swiftype to the right rail. This PR will back fill up to 5 links if there are frontmatter defined resources.

Related content in the right rail

---

STYLE_GUIDE.md

documented how search tags work in the style guide

added info on tags

---

src/components/MobileHeader.js
src/components/Sidebar.js

Change the input text to Filter so not to confuse users as we know how proper search.

updated input text

---

src/markdown-pages/collect-data/custom-events.mdx

Match formatting in the custom events guide as other pages do.

docs: match formatting in custom events guide

---

src/pages/index.js

Updated index.js for kubecon europe

Updated index.js for kubecon europe

---

src/markdown-pages/explore-docs/nr1-cli.mdx

no space looked bad so i fixed it.

added a br tag under the intro

---

COMPONENT_GUIDE.md
src/components/RelatedContentModules/Resources.js
src/markdown-pages/build-apps/build-hello-world-app.mdx
src/markdown-pages/build-apps/set-up-dev-env.mdx
src/markdown-pages/explore-docs/nr1-cli.mdx

- Added vscode ext to the right rail on several pages using url resources 
- added vscode ext tip section to several pages
- added a visual studio resource site tag
- updated component guide explaining how the right rail resources component works.

added vscode ext and updated component guide

---

COMPONENT_GUIDE.md

@jerelmiller  provided a code review and that PR was merged,  this updates the guide from his code review
https://github.com/newrelic/developer-website/pull/623

updated guide from code review

---

src/markdown-pages/automate-workflows/get-started-kubernetes.mdx

To address the issue of iframes not appearing in certain browsers I took the simple approach.
I also added a title tag to the iframe as it's good practice. :)
#626

added tip component to kub page

---

src/layouts/MainLayout.js

Closes #631 
Fixes the issue of the footer growing to a large size when viewing the size on a large resolution monitor.

Fix footer height on large resolution monitors

---

.github/workflows/fetch-related-content.yml
.github/workflows/release.yml

Adds branch protection changes for the changelog generation and the swiftype result generation.

Add missed branch protection changes for other jobs

---

src/components/PageLayout/PageLayout.js
src/components/RelatedContentModules/Contribute.js

Closes #644 
Updates the copy on the "File an issue" button to "Create an issue". Also adjusts the right-rail size to accommodate the larger button size.

Change "File an issue" button to "Create an issue"

---

src/markdown-pages/automate-workflows/kubernetes-helm-deployment.mdx

Typo: chats -> charts

---

src/markdown-pages/build-apps/publish-deploy.mdx

also added links to the list of topics covered in the page.
Wanted to add the links because this is a pretty long page.
* [issue]()

slight wording fix

---

src/markdown-pages/build-apps/permission-manage-apps.mdx
src/markdown-pages/build-apps/publish-deploy.mdx

update to previous PR - per @jpvajda I moved a section on versions on the permissions page to the "publish" section on the publish-deploy page.
I had some npm errors so did the end run. Please ensure there's not something weird in the code.
* [466](https://github.com/newrelic/developer-website/issues/466)

Manage apps page

---

src/markdown-pages/build-apps/build-hello-world-app.mdx

updated video https://www.youtube.com/watch?v=7omo0qHxku8&feature=youtu.be
* [531]()

`chore` update video

---

src/pages/index.js

Reverts newrelic/developer-website#706

Revert "Revert "Update countdown timer after CFP closes""

---

src/pages/nerd-days.js

CFP is now closed, removing copy about CFP.

Remove CFP content

---

src/components/Countdown/CountdownContainer.js
src/pages/all-things-open.js
src/pages/nerd-days.js

Fix lint errors currently on the `main` branch that makes it difficult to push new changes

Fix lint errors

---

src/pages/index.js

changing boring "register" link that's just floating to cool primary button link per guidance by @LizBaker 🥳

Update register link to register button on homepage

---

src/markdown-pages/explore-docs/nerdstorage.mdx

Update the storage limit because they have been increased.
You can review the limits on Nerd Store project:
https://source.datanerd.us/nr1-platform-services/nerd-store/
* [[NS] Update external documentation with new limits](https://newrelic.atlassian.net/browse/NR1SERVICE-1749)

docs: Update storage limits

---

package-lock.json
package.json

Upgrading gatsby-theme-newrelic to 1.9.1

---

src/pages/emea-nerd-days.js

Nerd Days EMEA won't have Call For Proposal hence the section is not needed.

feat: Remove call for papers section for EMEA

---

src/pages/nerd-days.js

correct apj/emea registration links

fix: corrected registration links

---

src/layouts/MainLayout.js

Repositions sidebar to top of page

---

src/pages/emea-nerd-days.js
src/pages/nerd-days.js

update emea dates

---

src/pages/nerd-days.js

Fixed spelling errors in agenda

small agenda bug fixes

---

src/pages/nerd-days.js

Agenda: update the keynote announcement
APJ reg: switch date to TBD, per request by APJ team as they figure out final dates

minor updates

---

COMPONENT_GUIDE.md
CONTRIBUTING.md
STYLE_GUIDE.md
src/markdown-pages/automate-workflows/5-mins-tag-resources.mdx

- updated the component guide to reference to the announcement banner documentation
- added a TOC to the component guide
- updated the style guide to include how to updated TOCs in markdown files
- add split instructions to contributing file

updated component and style guide

---

src/components/MarketoForm/MarketoForm.js
src/hooks/useMarketoForm.js

Fixes a linting error that is blocking @mmfred!

chore: fixes linting error

---

src/announcements/dev-portal-vote.mdx
src/announcements/nerd-days-registration.mdx

- added an announcement for the dev portal contest
- added an announcement for nerd days event

Announce banner dev portal & nerd days event

---

src/markdown-pages/build-apps/add-nerdgraphquery-guide.mdx

Addressed issue mentioned here https://github.com/newrelic/developer-website/issues/750
* [issue]()

Updated documentation to add "npm install"

---

src/announcements/dev-portal-vote.mdx
src/announcements/nerd-days-registration.mdx

Reverts newrelic/developer-website#755

Revert "Announce banner dev portal & nerd days event"

---

package-lock.json
package.json
src/announcements/dev-portal-vote.mdx
src/announcements/nerd-days-registration.mdx

Original PR: #755 
Reverts newrelic/developer-website#761
**DO NOT MERGE UNTIL RESOLVED**
* Closes #760

Revert "Revert "Announce banner dev portal & nerd days event""

---

src/markdown-pages/build-apps/map-pageviews-by-region.mdx

Changing back-ticks to single quotes
None
None

Fixing Typo for back ticks to signal quotes

---

src/pages/nerd-days.js

APJ team just confirmed they're moving up their date to Oct 22, updating date.

Small Fix: Update date for APJ Event

---

src/pages/index.js

Swapped the image of nerd days for this rad video.

Home video swap

---

STYLE_GUIDE.md
src/markdown-pages/automate-workflows/get-started-kubernetes.mdx

- update style guide to include where to store image files and video files when contributing
- a tag updated to the kubernetes guide, seemed to removed then readded in this commit

updated style guide to explain how to store images / video files

---

src/pages/emea-nerd-days.js

Updating EMEA Calendar for the Nerd Days
* [issue]()

feat: Update EMEA calendar

---

src/pages/apj-nerd-days.js

update apac event page with agenda

---

.github/workflows/fetch-related-content.yml
.github/workflows/release.yml

* updates the branch name in the workflow files

chore: update branch name in workflow files

---

package-lock.json
package.json
src/components/MarketoForm/MarketoForm.js
src/components/MarketoForm/marketo.scss
src/components/Spinner.js
src/hooks/useMarketoForm.js
src/hooks/useScript.js

Updates the marketo form to fix a few things:
* Refactor to use a state machine to better determine how the marketo form was able to load
* Show error states if the marketo form was unable to load.
* Add a loading spinner when the form is loading
* Fix issue where submitting the form redirected to the thank you page, then a second later, redirected back to the nerd days page
* Update the button style to better match the rest of the site

Marketo form updates

---

src/pages/emea-nerd-days.js

Fix agenda for emea
* [issue]()

feat: Fix emea time in agenda

---

src/pages/emea-nerd-days.js

Update emea agenda: Timezone

---

CONTRIBUTING.md

updated contributing with develop branch use
https://github.com/newrelic/developer-website/issues/598

updated contributing with develop branch use

---

src/markdown-pages/explore-docs/nerdstorage.mdx

- Called out that nerdstorage shouldn't be used to store secrets since it's not encrypted at this moment
- Also included linter auto fixes ;)

added tip about nerdstorage

---

src/data/sidenav.json
src/markdown-pages/explore-docs/intro-to-sdk.mdx
src/markdown-pages/explore-docs/nerdstorage.mdx
src/markdown-pages/explore-docs/nerdstoragevault.mdx

Added a guide on the new feature for nerdstorageVault
Need feedback from the AppCat team to ensure I've documented this properly. 
#827

Nerdvault guide

---

src/markdown-pages/explore-docs/nerdstoragevault.mdx

Sentence case fix

---

src/announcements/dev-portal-vote.mdx
src/data/sidenav.json

Now that nerd-days is over, this nav element is moved to past events.
Activated voting announcement

moved nerdays to past events + activate vote announcement

---

src/markdown-pages/automate-workflows/get-started-terraform.mdx

This PR updates the "Set Up New Relic with Terraform" guide to use the latest version of the Terraform provider and to include alerts for the 4 golden signals of monitoring. 
Checkout branch, run `npm install && npm start`, then navigate to http://localhost:8000/automate-workflows/get-started-terraform to view the updated guide. 
- https://github.com/newrelic/developer-toolkit/issues/37

feat(guides): add golden signal alerts to the Terraform guide

---

src/pages/nerd-days.js

Remove the AMER nerd days registrations form

Remove amer form

---

src/markdown-pages/explore-docs/nerdstoragevault.mdx

The example for nerdStorageVaultWriteSecret needs this update for it to be a working query. Also added the error type field.

Fix nerdStorageVaultWriteSecret example

---

src/pages/emea-nerd-days.js

fix: Update emea agenda

---

src/pages/index.js

Update homepage countdown to focus on Nerd Days EMEA

Nerd days updates

---

gatsby-config.js
src/markdown-pages/automate-workflows/5-mins-tag-resources.mdx
src/markdown-pages/automate-workflows/automated-tagging.mdx
src/markdown-pages/automate-workflows/get-started-kubernetes.mdx
src/markdown-pages/automate-workflows/get-started-new-relic-cli.mdx
src/markdown-pages/automate-workflows/get-started-terraform.mdx
src/markdown-pages/automate-workflows/kubernetes-helm-deployment.mdx
src/markdown-pages/build-apps/add-nerdgraphquery-guide.mdx
src/markdown-pages/build-apps/add-query-mutate-data-NerdStorage.mdx
src/markdown-pages/build-apps/add-time-picker-guide.mdx
src/markdown-pages/build-apps/build-hello-world-app.mdx
src/markdown-pages/build-apps/publish-deploy.mdx
src/markdown-pages/collect-data/add-custom-attributes.mdx
src/markdown-pages/explore-docs/nerdpack-file-structure.mdx
src/markdown-pages/explore-docs/nerdstoragevault.mdx
src/markdown-pages/explore-docs/newrelic-CLI.mdx
src/markdown-pages/explore-docs/query-and-store-data.mdx

With the release of the guide improvements, we now have a terminal component available. This PR goes through each doc and makes sure that terminal commands specify the code block as a shell so that the terminal component is rendered. 
Other miscellaneous update:
* Ensure there was syntax highlighting where appropriate by adding the proper language definition
* Fix some small formatting issues

Edit pass syntax highlighting

---

src/data/additionalDocs.js

Fix a small typo, updating `nerlet` to `nerdlet`
N/A
N/A
N/A

chore: fix nerlet typo

---

src/markdown-pages/build-apps/build-hello-world-app.mdx
src/markdown-pages/build-apps/set-up-dev-env.mdx

I added the new vs code extension pack to tips and the related resources on these 2 guides.

updated guides vs code extension pack

---

src/components/Sidebar.js

Updates left nav sidebar placeholder text. 
Closes [newrelic/docs-website#79](https://github.com/newrelic/docs-website/issues/179)
* [newrelic/docs-website#79](https://github.com/newrelic/docs-website/issues/179)

refactor: change left nav input placeholder text

---

src/pages/apj-nerd-days.js
src/pages/emea-nerd-days.js

Per request, this updates the marketo IDs to point to the correct instances.

Update APJ and EMEA Nerd Days marketo IDs

---

src/hooks/useMarketoForm.js
src/pages/apj-nerd-days.js
src/pages/emea-nerd-days.js

Updates to use the new marketo form instance and the munchkin IDs. Also ensures that if there are errors loading the form that it does not crash the page.

Fix marketo form errors

---

gatsby-ssr.js
src/components/Seo.js

Changes the value for the google site verification content. 
Partially addresses #888

Google Verification Content Change

---

src/markdown-pages/automate-workflows/automated-tagging.mdx

fixed path to hello.aws.json configuration file. 
Relates to issue: https://github.com/newrelic/developer-website/issues/958

chore: fixed path to hello.aws.json file

---

CHANGELOG.md
package.json
src/markdown-pages/automate-workflows/automated-tagging.mdx
src/markdown-pages/automate-workflows/diagnose-problems/index.mdx
yarn.lock

This includes some minor guide improvements.

Guide Updates Merge to Main

---

package.json
src/components/MDXContainer.js
yarn.lock

Adds the table component from the theme to the MDXContainer

Table added to dev site from theme

---

package.json
yarn.lock

This should resolve our build issues 🤞

Update Theme to `1.16.1`

---

src/markdown-pages/automate-workflows/get-started-terraform.mdx

This is Zach from NR docs team.
* [issue]()

Changing 'personal API key' to 'user key'

---

src/markdown-pages/automate-workflows/get-started-kubernetes.mdx

This is Zach from NR docs team.
* [issue]()

Changing 'personal key' to 'user key'

---

src/markdown-pages/collect-data/get-started-nerdgraph-api-explorer.mdx

This is Zach from NR docs team.
* [issue]()

change 'API key' to 'user key', w/ some doc links

---

src/markdown-pages/automate-workflows/5-mins-tag-resources.mdx

Some edits to the file.
I hadn't done a thorough edit pass previously.
I have some notes to add for the writer to review. I'll add them in the PR.

Edit pass Quickly tag resources

---

package.json
yarn.lock

This PR updates the dev site theme which includes the updated global footer
https://github.com/newrelic/opensource-website/issues/663

fix: updated theme

---

src/markdown-pages/automate-workflows/automated-tagging.mdx
src/markdown-pages/automate-workflows/diagnose-problems/index.mdx

Update demo configuration URLs for demo-catalog.
* [Update the catalog readme to add more details on story/contributing](https://github.com/newrelic/demo-catalog/pull/4)

Update URLs for demo-catalog

---

.github/pull_request_template.md
CONTRIBUTING.md

This PR updates our PR template and contributor guide to be more clear on how to use conventional commits. 
* [issue]()

chore: updating pr template and contributing file

---

src/data/sidenav.json
src/markdown-pages/components/charts/area-chart.mdx
src/markdown-pages/components/charts/bar-chart.mdx
src/markdown-pages/components/charts/billboard-chart.mdx
src/markdown-pages/components/charts/chart-group.mdx
src/markdown-pages/components/charts/funnel-chart.mdx
src/markdown-pages/components/charts/histogram-chart.mdx
src/markdown-pages/components/charts/index.mdx
src/markdown-pages/components/charts/json-chart.mdx
src/markdown-pages/components/charts/line-chart.mdx
src/markdown-pages/components/charts/pie-chart.mdx
src/markdown-pages/components/charts/scatter-chart.mdx
src/markdown-pages/components/charts/sparkline-chart.mdx
src/markdown-pages/components/charts/stacked-bar-chart.mdx
src/markdown-pages/components/charts/table-chart.mdx
src/markdown-pages/components/heatmap-component.mdx

Reorganized chart component content and added an overview guide.
Please sanity check that I didn't break links by updating the hierarchy.
https://github.com/newrelic/developer-website/issues/975

Charts guide

---

src/markdown-pages/components/charts/index.mdx

- adds resource links and tags to chart index page 
- prettier linter improvments

chore: added resource links and tags

---

src/data/sidenav.json
src/pages/developer-events.js

- Updates the Developer Events landing page
- Updates the Developer Events navigation

Event updates

---

src/markdown-pages/explore-docs/nr1-cli.mdx

This PR fixes a broken link referencing the nr1-subscription section.

chore: fixed broken link

---

CONTRIBUTING.md

Relates to #1077
Updates the [contributing](CONTRIBUTING.md) guide to explain how to upgrade the NR1 SDK.

Update the contributing guide with info on updating the NR1 SDK documentation

---

.github/workflows/build-cache.yml
.github/workflows/validate-pr.yml

closes https://github.com/newrelic/docs-website/issues/699

Adds both the validate PR action and caching to the dev site

---

src/announcements/gatsby-conf.mdx

This PR adds an announcement banner to the dev site.

chore: added banner

---

src/markdown-pages/automate-workflows/diagnose-problems/index.mdx

This fixes two relative links in the Acme Telco Lite guide.

Fix links in Acme Telco Lite guide

---

src/markdown-pages/explore-docs/newrelic-cli.mdx

This PR adds the new decode  functionality to the CLI doc on the site.

chore:cli docs update

---

src/markdown-pages/explore-docs/newrelic-cli.mdx

This PR fixes the order of the decode command and puts it in alphabetical order

chore: reorders commands

---

src/markdown-pages/terraform/terragrunt-configuration.mdx

Fixed spelling error in guide meta data

---

src/markdown-pages/automate-workflows/diagnose-problems/index.mdx

Fixed link to catalog

---

src/data/sidenav.json

I added the Terraform mini-site and its children developer guides to the side nav.

Add terraform minisite to sidenav

---

src/pages/index.js

Remove the repeated text "software tools"
* [issue]()
```bash
```
* for minor functional …

chore: removing duplicate text from index.js

---

src/data/relicansData.js

Simple URL correction since the existing URL leads to an error page "This profile is not available".

Correct Ali's LinkedIn URL

---

src/markdown-pages/build-apps/build-visualization.mdx

* [issue]()
```bash
```
* for minor functional corrections to code.
```bash
git commit -m …
```

chore: Update custom visualizations guide

---

src/markdown-pages/build-apps/build-visualization.mdx

Currently when creating a Nerdpack, the default outcome is to add a `nerdlets/` and `launchers/` folder in the Nerdpack. This is unnecessary and potentially confusing if you just want to create a visualization. I've gotten some feedback that it isn't clear you can remove those folders and have the Nerdpack continue working so I'd like to add a note in this guide somewhere. I think where I've added it is a good place but would welcome feedback on that. Thanks!
N/A
* [issue]() N/A
If relevant, add screenshots here. N/A
Please help the maintainers by leveraging the following [conventional …

chore: Adds note on removing launchers and nerdlets

---

src/pages/nerdlog.js

Fixing some eslint problems on this PR
https://github.com/newrelic/developer-website/pull/1182

chore: eslint fixes to PR #1182

---

src/markdown-pages/explore-docs/nerdpack-file-structure.mdx

3 broken links to the NR CLI have been updated to the correct links.
https://developer.newrelic.com/explore-docs/nerdpack-file-structure
Broken links:
https://developer.newrelic.com/explore-docs/nr1-cli

chore: update broken links to nrcli

---

src/pages/nerdlog-thank-you.js
src/pages/nerdlog.js

feat(page): creating nerdlog thank you page

---

COMPONENT_GUIDE.md

New component guide for tutorial component

---

src/markdown-pages/build-apps/permission-manage-apps.mdx

Emphasizing the "cannot" in basic user limitations
* [issue]()
```bash
```
* for minor …

Emphasizing the "cannot" in basic user limitations

---

CONTRIBUTING.md

I'm new relic employee, docs team, and I think that NR slack channel name was out of date.

Think the slack channel was out of date

---

src/components/DevSiteSeo.js

Added 'summary_large_image' for Twitter so card will fully unfurl on Twitter.
Enables Twitter to display large image for increased shareability. 

Chore: Update DevSiteSeo.js to include 'summary_large_image'

---

src/pages/nerdlog-thank-you.js

Fixes eslint errors on this [PR](https://github.com/newrelic/developer-website/pull/1207)

Eslint fixes on nerlog-thank-you.s

---

src/markdown-pages/explore-docs/nr1-nerdpack.mdx

Update `nr1 nerdpack` API docs.
These are auto-generated by scraping `nr1 nerdpack --help`, so language updates should happen in the `nr1` repo.

chore: update nr1 nerdpack docs

---

gatsby-browser.js
gatsby-config.js

This PR adds the configuration for tessen and remove the individual GA tracking code so we can leverage all the goodness of Tessen and Segment. 🎸

chore: adds tessen configuration

---

gatsby-config.js

This PR sets the segment write key to the correct one for the developer.newrelic.com source in Segment.

chore: updated segment write key

---

src/markdown-pages/build-apps/permission-manage-apps.mdx
src/markdown-pages/build-apps/set-up-dev-env.mdx
src/markdown-pages/explore-docs/nr1-cli.mdx

This is a revised PR related to the previous PR https://github.com/newrelic/developer-website/pull/1217. I had technical problems and couldn't edit it so I started over.
I think I addressed all concerns. I think it's looking better. Thank you all.

Update to Nerdpack permissions doc

---

src/markdown-pages/build-apps/customize-visualizations-with-configuration.mdx

The new visualization template will set the `accountId` configuration field to have a type of `account-id`. This is not yet ready to merge, just getting into place for once the visualization template update is merged.
* [issue]()
* for minor changes / …

Updates to match template for visualization

---

src/data/nav.yml
src/markdown-pages/build-apps/advanced-config.mdx
src/markdown-pages/build-apps/build-hello-world-app.mdx
src/markdown-pages/build-apps/build-visualization.mdx

Adds advanced config guide to establish a source-of-truth guide for this content, rather than it living in the "Hello, world" tutorial.
Fixes: https://github.com/newrelic/developer-website/issues/1235

chore: Add advanced config guide

---

src/markdown-pages/build-apps/create-an-ab-test-application/install-sdk.mdx

Clarify which profile name, user key, and region the user should use for their `nr1` profile.

chore: Clarify profile values

---

src/markdown-pages/build-apps/serve-publish-subscribe/serve.mdx

Add a new **Serve your Nerdpack** guide.
This is intentionally hidden for now, because it's part of a bigger restructure.

feat: Create new Serve you Nerdpack doc

---

src/pages/index.js

fix: correct spelling of FutureStack

---

src/markdown-pages/build-apps/create-an-ab-test-application/chart-group.mdx
src/markdown-pages/build-apps/create-an-ab-test-application/chart-headings.mdx
src/markdown-pages/build-apps/create-an-ab-test-application/confirmation-modal.mdx
src/markdown-pages/build-apps/create-an-ab-test-application/end-test.mdx
src/markdown-pages/build-apps/create-an-ab-test-application/first-chart.mdx
src/markdown-pages/build-apps/create-an-ab-test-application/grid.mdx
src/markdown-pages/build-apps/create-an-ab-test-application/navigation.mdx
src/markdown-pages/build-apps/create-an-ab-test-application/nerdstorage.mdx
src/markdown-pages/build-apps/create-an-ab-test-application/nerdstoragevault.mdx
src/markdown-pages/build-apps/create-an-ab-test-application/nrql-customizations.mdx
src/markdown-pages/build-apps/create-an-ab-test-application/nrql.mdx
src/markdown-pages/build-apps/create-an-ab-test-application/persist-selected-version.mdx
src/markdown-pages/build-apps/create-an-ab-test-application/pie-charts.mdx
src/markdown-pages/build-apps/create-an-ab-test-application/platform-state-context.mdx
src/markdown-pages/build-apps/create-an-ab-test-application/table-charts.mdx
src/markdown-pages/build-apps/create-an-ab-test-application/third-party-service.mdx
src/markdown-pages/build-apps/create-an-ab-test-application/version-descriptions.mdx

Per course review, I've updated the serve steps to clarify how to view your app in New Relic in every tutorial.

chore: Clarify "view app" instructions per course review

---

src/markdown-pages/build-apps/create-an-ab-test-application/create-nerdpack.mdx

Just a small update but I noticed we don't include `visualization` in the nerdpack definition and it should be included.
@jaesius & @alexronquillo just want to flag this to make sure its ok with y'all since I believe its part of the NRU programmability course

chore: Add viz to nerdpack defition

---

src/pages/relicans.js
src/pages/relicans.module.scss

Updated based on recommendations by product designers, left-aligned `Meet the Relicans` title and put a border around each relicans tile

chore: Update Meet the Relicans section style

---

src/data/nav.yml

add futurehack nav

---

src/markdown-pages/explore-docs/intro-to-sdk.mdx

This PR updates the definition of nerdlet API and links the correct location

fixed nerdlet definition

---

gatsby-config.js

Added flags that are on Docs site to align builds
```
flags: {
DEV_SSR: true,
PRESERVE_WEBPACK_CACHE: true,
PRESERVE_FILE_DOWNLOAD_CACHE: true,
}
```

feat: adding feature flags for faster building

---

package.json
yarn.lock

update gatsby package to version 3.5.
Resolves #1310

fix: update to gatsby 3.5

---

src/markdown-pages/build-apps/add-nerdgraphquery-guide.mdx
src/markdown-pages/build-apps/add-query-mutate-data-NerdStorage.mdx
src/markdown-pages/build-apps/add-time-picker-guide.mdx
src/markdown-pages/build-apps/advanced-config.mdx
src/markdown-pages/build-apps/attach-nerdlet-to-entities.mdx
src/markdown-pages/build-apps/build-hello-world-app.mdx
src/markdown-pages/build-apps/create-an-ab-test-application/install-sdk.mdx
src/markdown-pages/build-apps/howto-use-nrone-table-components.mdx
src/markdown-pages/build-apps/map-pageviews-by-region.mdx
src/markdown-pages/build-apps/serve-publish-subscribe/catalog.mdx
src/markdown-pages/build-apps/serve-publish-subscribe/publish.mdx
src/markdown-pages/build-apps/serve-publish-subscribe/serve.mdx
src/markdown-pages/build-apps/serve-publish-subscribe/subscribe.mdx
src/markdown-pages/build-apps/serve-publish-subscribe/tag.mdx

We should make sure that guides that use the `nr1` CLI instruct users to update to the latest version.

chore: Make sure users update nr1

---

src/pages/students.js

Student edition

---

src/data/relicansData.js

My bio information was outdated

Update my bio

---

package.json
src/data/relicansData.js
yarn.lock

Handle case when cookies are blocked.
Closes https://github.com/newrelic/docs-website/issues/2293

fix: update to theme version that handles blocked cookies

---

src/pages/students.js
src/pages/students.module.scss

this pr fixes a bug on the students page and prettier took care of some linting best practices. 
Resolved this console warning:
```
warn ./src/pages/students.js
Attempted import error: 'section' is not exported from './students.module.scss' (imported as 'styles').
warn ./src/pages/students.js
Attempted import error: 'section' is not exported from './students.module.scss' (imported as 'styles').
warn ./src/pages/students.js
Attempted import error: 'section' is not exported from './students.module.scss' (imported as 'styles').
warn ./src/pages/students.js
Attempted import error: 'answer' is not exported from './students.module.scss' (imported as 'styles').
warn ./src/pages/students.js
Attempted import error: 'answer' is not exported from './students.module.scss' (imported as 'styles').
warn …
```

chore: fixes a few bugs

---

src/templates/ObservabilityPackDetails.js

add standard intro text to tabs pages

---

src/components/InstallButton.js
src/templates/ObservabilityPackDetails.js

Adds the Install Button component to the Pack Details page and instruments it with NR Browser and Tessen

feat: add install button and instrument

---

src/pages/observability-packs.js

chore: add pack count to filter dropdown

---

package.json
src/templates/ObservabilityPackDetails.js
yarn.lock

* added final copy for dashboards, alerts, synthetics
* since there wasn't any data for synthetics & alerts, added placeholder data & updated query to use data
Resolves: #1394

Add final copy for dashboards, alerts, synthetics

---

package.json
yarn.lock

Bump theme to v2.5
https://github.com/newrelic/gatsby-theme-newrelic/releases/tag/v2.5.0

Bump theme to v2.5

---

src/pages/observability-packs.js

Add updated copy for the "Build your own observability pack" tile

---

gatsby-config.js
plugins/gatsby-source-newrelic-sdk/src/constants.js
plugins/gatsby-source-newrelic-sdk/src/getPropTypes.js
src/data/nav.yml

updating the component SDK to version 2837.
Closes #1413
Be sure to double check the components in the preview to be sure that nothing is broken.

chore: update sdk version

---

gatsby-config.js

Per Zoe and Austin, allow full url paths in referrer

Change referrer to allow full url paths

---

src/markdown-pages/explore-docs/nerdpack-file-structure.mdx

Fixing broken link from https://github.com/newrelic/docs-website/issues/3027.

Broken link, fixing

---

package.json

This PR bumps the theme to the current version

bumps theme

---

.github/workflows/fetch-quickstarts.yml
gatsby-config.js
gatsby-node.js
package.json
scripts/actions/__tests__/fetch-quickstarts.test.js
scripts/actions/fetch-quickstarts.js
src/components/InstallButton.js
src/components/quickstarts/EmptyTab.js
src/data/nav.yml
src/data/quickstarts.json
src/pages/instant-observability.js
src/templates/QuickstartDetails.js

Rename most things from "Observability pack" to "quickstart"

Quickstarts rename

---

yarn.lock

The package.json is currently ahead of the yarn.lock and causing some issues. This gets the yarn.lock up to date.

Sync yarn.lock with package.json

---

src/components/MobileQSFilter.js
src/components/PackTile.js
src/components/Tabs/BarItem.js
src/pages/instant-observability.js
src/templates/QuickstartDetails.js

* fix duplicate tessen track calls
* add tracking to view repo button
* change observability pack to quickstart where found
Closes: #1538

chore: add tessen calls for important user actions

---

src/templates/QuickstartDetails.js
yarn.lock

chore: move CTA buttons from page tools

---

src/templates/QuickstartDetails.js

Adds a cookie with a quickstart ID value upon clicking install
Closes https://github.com/newrelic/developer-website/issues/1518

Add cookie

---

src/components/quickstarts/QuickstartDataSources.js
src/templates/QuickstartDetails.js
yarn.lock

This PR adds the approve language to the data source tab and fixes a type in the quickstart right rail.

Data source tab content

---

src/templates/QuickstartDetails.js

This PR adds 1 rem padding to the H1 header and revises how to use this quickstart text.

chore: adds H1 padding + how to use update

---

src/components/IOBanner.js

fixes banner text and sets proper casing as defined by marketing 
- Capitalize so that it says “Instant Observability”

chore: casing fix

---

src/components/quickstarts/QuickstartOverview.js
src/templates/QuickstartDetails.js

Moves `summary` to top and `description` to bottom. Updates some style for `summary` area.
Closes https://github.com/newrelic/developer-website/issues/1630

refactor: small updates to details page and overview tab

---

src/components/quickstarts/QuickstartAlerts.js
src/components/quickstarts/QuickstartDashboards.js
src/components/quickstarts/QuickstartDataSources.js

this PR changes the use of .name to .title

chore: replaces name with title

---

scripts/actions/fetch-quickstarts.js
src/components/InstallButton.js
src/data/quickstarts.json
src/pages/instant-observability.js
src/templates/QuickstartDetails.js
src/types.js

This PR only shows the 'install quickstart' text if it has installPlans present.
* [issue](https://github.com/newrelic/developer-website/issues/1644)
* for minor non-functional changes / additions to github actions, github templates, package or config updates, …

Dynamically change install button if there are installPlans

---

.github/stale.yml

chore: relaxing  stale bot

---

gatsby-config.js
src/layouts/MainLayout.js

David said OneTrust wasn't reporting any cookies and he may need to tweak something. Until that's done, need to revert to using cookie consent component until david gives us go ahead.

Revert switch to OneTrust

---

gatsby-config.js

* Sets the Content-Security-Policy to allow the sites contents to
embedded in an iframe on the newrelic domain

fix: allow embed content in iframes

---

.github/workflows/release.yml

Update node version for release and lock semantic release version

fix Github releases

---

.github/stale.yml

chore: adjusts close time

---

gatsby-config.js

chore: add skilljar cdn to list of domains

---

scripts/list-quickstart-urls.js
src/components/InstallButton.js
src/data/constants.js
src/utils/get-pack-nr1-url.js

The guided install will be opened in a card on top of the explorer nerdlet.
* [issue]()
```bash
git commit -m "chore: adjusting config and …
```

Open guided install nerdlet in a card

---

src/components/PackTile.js

chore: add default summary

---

src/data/nav.yml
src/markdown-pages/collect-data/network-performance-monitoring.mdx

Add a new Network Performance Monitoring lab

Newtork Performance Monitoring lab

---

src/components/quickstarts/QuickstartOverview.js

Tweaks some heading / markdown description styles on overview tab to make it more readable / align with in-product style as much as possible
Closes https://github.com/newrelic/developer-website/issues/1696

Updating heading style on overview tab

---

src/components/IOBanner.js
src/components/quickstarts/BetaBanner.js
src/pages/instant-observability.js
src/templates/QuickstartDetails.js

Adds a temporary beta banner to the IO marketplace
Closes #1711

Add beta banner to marketplace

---

src/components/quickstarts/BetaBanner.js

Updates the beta banner with new copy

Update beta banner copy

---

src/data/constants.js

More url updates!

---

src/pages/students.js
src/templates/ApiReferenceTemplate.js
src/templates/ComponentReferenceTemplate.js

Looks like we have a few changes that shouldn't be in this branch. This restores them to the correct form.

chore: restore develop version

---

package.json
yarn.lock

Bump theme to latest for IO

---

src/utils/get-pack-nr1-url.js

This will use our soon-to-be live launcher for the quickstart nerdlet
should not be merged until the launcher is ...launched

Use quickstart launcher

---

src/components/quickstarts/BetaBanner.js

Closes https://github.com/newrelic/newrelic-quickstarts/issues/414

Replace beta with preview in callout

---

src/markdown-pages/contribute-to-quickstarts/index.mdx

After the release of New Relic I/O, I updated the landing page of quickstarts to include the video.

chore: updated landing page video for I/O

---

gatsby-config.js
package.json
yarn.lock

- Update to fix external links. This should add back the instrumentation that we have been missing.
Resolves: #1850

Update theme for missing tessen events

---

src/pages/instant-observability.js

Closes https://github.com/newrelic/developer-website/issues/1848

Refactor disabled checks and add additional filtering

---

CONTRIBUTING.md
gatsby-config.js

- this PR updates the instructions for an SDK bundle update
- as well as update the sdk release version

chore: updating one core sdk instructions

---

src/data/instant-observability-categories.json

Adding a notification as per Slack request

feat: add notification category

---

package.json
yarn.lock

Pull in latest version of the theme which should have updated tessen event names.

chore: update theme to latest

---

src/markdown-pages/collect-data/pixie-lab/index.mdx
src/markdown-pages/collect-data/pixie-lab/scenario-1.mdx
src/markdown-pages/collect-data/pixie-lab/scenario-2.mdx
src/markdown-pages/collect-data/pixie-lab/set-up-env.mdx

Add Windows support to pixie lab

chore: add windows support to pixie lab

---

src/experiments/super_tiles/components/CodeStreamTile.js
src/experiments/super_tiles/components/GuidedInstallTile.js

* a couple places are still using old tessen signatures, so updating
them to work with new changes recently made.

chore: updating remaining tessen events that were forgotten

---

package.json
yarn.lock

Pull in the new theme version to get the Global Header changes

Update theme to pull in new header

---

CHANGELOG.md
package.json

Release 🚀 

---

src/components/DevSiteSeo.js

[x] Add the 6 new URLS. 
~~[ ] Address the `Multiple userscripts installed` error~~  - Moved to a [new ticket.](https://github.com/newrelic/developer-website/issues/1927)
Closes https://github.com/newrelic/developer-website/issues/1896

chore: add crazyegg script to top 6 quickstarts

---

src/markdown-pages/terraform/index.mdx
src/markdown-pages/terraform/terragrunt-configuration.mdx

Language edits of old Terraform/Terragrunt docs

Review terraform

---

src/pages/instant-observability.js
src/utils/customNewRelicEvent.js

Makes a call to the [New Relic Events API](https://docs.newrelic.com/docs/data-apis/ingest-apis/introduction-event-api/) for every NerdGraph API request. Logs the query parameters, whether or not it was successful, and the error message (if present).
~I'm not sure if we will have access to the environment variables at the time that this code gets executed. If anyone knows more about this, I'd love some help figuring it out.~
* Relates to #1857

SSR Instrumentation

---

CONTRIBUTING.md

This PR explains that the developer center now updates terms automatically based on this terms mdx file.

chore: updated developer terms process

---

gatsby-browser.js

changes are only applied to I/O

remove auto-scroll for I/O

---

src/components/PackImg.js
src/components/PackTile.js
src/images/build-your-own.svg
src/images/default-logo-background.svg
src/pages/instant-observability.js

Decreases the size of the quickstart tiles.

Smaller quickstart tiles

---

src/components/IOBanner.js
src/components/PackTile.js
src/data/constants.js
src/layouts/QuickStartLayout.js
src/pages/instant-observability.js

Final design changes for I/O mobile

Clark/mobile io updates - 1964

---

src/pages/instant-observability.js

Remove grid area causing the content to be pushed down on mobile views

fix: odd mobile styling

---

src/markdown-pages/automate-workflows/error-inbox/index.mdx

Correct typo in Errors Inbox lab description

Correct typo in Errors Inbox lab description

---

src/components/GuidedInstallTile.js
src/components/IOBanner.js
src/components/PackTile.js
src/components/SegmentedControl.js
src/pages/instant-observability.js

chore: Styling nits for I/O

---

src/pages/index.js

A small copy change to reflect the new number of quickstarts we have
* [issue]() …

Update number of quickstarts to 450 in index page

---

src/markdown-pages/build-apps/ab-test/demo-setup.mdx

spelling error

---

src/markdown-pages/automate-workflows/get-started-terraform.mdx

fixes link to terraform CLI

---

gatsby-node.js

Updating the code for a redirect in an attempt to make it a true 301 redirect instead of a meta refresh

fix: remove statusCode and make all redirects NOT in browser for IO

---

gatsby-config.js
third_party_manifest.json

fix: undo changes to 3rd party manifest

---

.github/CODEOWNERS

- Created new [Docs Engineering Team](https://github.com/orgs/newrelic/teams/docs-engineering/)
- Added team as Admin to [Developer Site](https://github.com/newrelic/developer-website)
- Update `CODEOWNERS` file
Resolves https://github.com/newrelic/docs-website/issues/6562

Codeowners update for devsite

---

src/markdown-pages/contribute-to-quickstarts/build-a-quickstart/create-quickstart.mdx

- This PR adds a call out tip to explain what data isn't needed in dashboard JSON. 
- It also ran markdown linter to clean up misc linting improvements

chore: added content for quickstart creation

---

src/markdown-pages/collect-data/collect-data-from-any-source.mdx

Original-
curl -i -X POST https://log-api.newrelic.com/log/v1 \
-H "Content-Type: application/json" \
-H "Api-Key: $LICENSE_KEY" \
-d '[
"logs": [
{
"timestamp": 1593538496000,
"message": "User xyz logged in",
"service": "login-service",
"hostname": "login.example.com"
}
]
]'
New -
curl --location --request POST 'https://log-api.newrelic.com/log/v1' \
--header 'X-License-Key: $License_Key' \
--header 'Content-Type: application/json' \
--data-raw '[{
"logs": [{
"message": "User xyz logged in",
"service": "login-service",
"hostname": "login.example.com"
}]
}]'
If there are any related [GitHub Issues](https://github.com/newrelic/developer-website/issues) or JIRA …

Had to fix curl json payload syntax

---

src/markdown-pages/automate-workflows/error-inbox/index.mdx

Errors Inbox is now available in EU region.

Remove inaccurate callout about EU region

---

package.json
yarn.lock

bumping to the latest version of the theme

fix: theme bump to 6.0.2

---

src/markdown-pages/collect-data/index.mdx

Because I've removed a few docs in this area, the landing page was more empty (as I didn't realize it was auto-populating that based on files present), so I'm attempting to make it more functional.

Some improvements to 'Collect data' landing page

---

src/data/nav.yml
src/markdown-pages/automate-workflows/get-started-pulumi.mdx
src/markdown-pages/automate-workflows/index.mdx
src/markdown-pages/pulumi/get-started-pulumi.mdx
src/markdown-pages/pulumi/index.mdx

This PR adds an example of using [Pulumi](https://pulumi.com/docs) to create and manage New Relic alerts.
I did my best to use the Terraform example as a baseline, so hopefully this looks all right and generally conforms to conventions. Definitely open to any and all feedback. Thank you in advance! 🙌

Add Pulumi documentation

---

src/data/nav.yml
src/markdown-pages/build-apps/add-visualizations-to-dashboard.mdx
src/markdown-pages/explore-docs/custom-viz/build-visualization.mdx
src/pages/nerdlog.js

some changes to 'nerdlog' language which is apparently now chnagelog

fix(nerdlog): language changes to changelog

---

src/markdown-pages/automate-workflows/get-started-kubernetes.mdx
src/markdown-pages/automate-workflows/kubernetes-helm-deployment.mdx

These updates are required for the embedded Instruqt tracks to keep working. See the message in our shared Slack channel ([#org-newrelic](https://instruqt.slack.com/archives/C015V4RDC65/p1654523751120759)) for more context.

Update Instruqt track embed urls to include the token 

---

src/markdown-pages/automate-workflows/get-started-terraform.mdx

Small example fixes in the new notifications terraform examples.
* [issue]()
```bash
```
* …

chore(terraform): fix terraform examples

---

gatsby-node.js

Redirect the /students to new page 
* [issue]()
```bash
```
* for minor functional …

chore: add student program redirect

---

src/markdown-pages/build-apps/howto-use-nrone-table-components.mdx

Fixing instructions

---

.eslintrc.js
package.json
src/pages/index.js
src/pages/index.module.scss

- removed yarn 3.2.0 pkg manager from file
- Added css magic to some file at some point
- Changed out I/O video for generic observability video
- Updated content from I/O to links to the docs site

updating front page for docs

---

src/data/external-redirects.json

Fixes external redirects introduced in #2206

fix(sonic): fix broken terraform doc external redirects

---

.github/workflows/fetch-related-content.yml
.github/workflows/release.yml

This way when the token needs to be rotated (like now) it's easy 🎉

Use org level bot token

---

src/markdown-pages/automate-workflows/get-started-new-relic-cli.mdx

The comment for the account creation was not updated

chore: update get-started-new-relic-cli.mdx

---

src/markdown-pages/automate-workflows/5-mins-tag-resources.mdx

Changed the outdated cli commands to the new version

chore:update 5-mins-tag-resources.mdx

---

src/markdown-pages/build-apps/ab-test/navigation.mdx
src/markdown-pages/build-apps/ab-test/nrql.mdx
src/markdown-pages/build-apps/ab-test/platform-state-context.mdx

Fixing some issues in sample code related to accountIds attribute

Fixing some issues in sample code related to accountIds attribute

---

src/markdown-pages/explore-docs/custom-viz.mdx

Relic requested link from custom viz doc to the permissions doc

fix(custom viz): add permissions

---

gatsby-config.js
gatsby-node.js
package.json
src/components/DevSiteSeo.js
src/components/SignupLink.js
yarn.lock

Replace uses of Tessen for addPageAction(). Adds Segment config.

Sunset Tessen

---

.github/workflows/fetch-related-content.yml
.github/workflows/release.yml

replaces token associated with old opensource bot user

Replace token name used in action workflows
